cat("Welcome to ACC_immune_cells project.\n")
my_library_folder = "/sci/labs/yotamd/lab_share/avishai.wizel/R_projects/libs"
.libPaths(c(my_library_folder, .libPaths())) # make my library folder as default folder (default folder is not writable)
ulimit::memory_limit(30000) # Limit ram to avoid crash
require(pheatmap,quietly = T)
require(Seurat,quietly = T)
require(ggplot2,quietly = T)
require(data.table,include.only = c("fread","fwrite"),quietly = T)
require(devtools,quietly = T)
require(SourceFromGithub,quietly = T)
require(clusterProfiler,quietly = T)
require(msigdbr,quietly = T)
require(dplyr,quietly = T)
require(My.rmd.template)
require(print.rmd.tabs)
require(tidyr ,quietly = T)
require(stringr ,quietly = T)
require(SeuratDisk ,quietly = T)
require(conflicted,quietly = T)
conflict_prefer(name = "select", winner = "dplyr",quiet = T)
conflict_prefer(name = "filter", winner = "dplyr",quiet = T)
