cat("Welcome to ACC_immune_cells project.\n")
.libPaths(c("/usr/local/lib/R/site-library"    , .libPaths())) 
.libPaths(c("/usr/local/lib/R/library"    , .libPaths()))                        

my_library_folder = "/sci/labs/yotamd/lab_share/avishai.wizel/R_projects/libs"
.libPaths(c(my_library_folder, .libPaths())) # make my library folder as default folder (default folder is not writable)
ulimit::memory_limit(30000) # Limit ram to avoid crash
# .libPaths( c("/sci/labs/yotamd/lab_share/avishai.wizel/R_projects/libs/ComplexHeatmap_2.25.2/",.libPaths()) )
library(magrittr,lib.loc = "/sci/labs/yotamd/lab_share/avishai.wizel/R_projects/libs/ComplexHeatmap_2.25.2/")

library(igraph, lib.loc = "/usr/local/spack/opt/spack/linux-debian12-x86_64/gcc-12.2.0/r-igraph-1.4.2-lxqmjthw2lo45ggzwhg3x47ehnezig22/rlib/R/library")
library(ComplexHeatmap,lib.loc = "/sci/labs/yotamd/lab_share/avishai.wizel/R_projects/libs/ComplexHeatmap_2.25.2/")
library(Matrix)
library(stringi,lib.loc = "/usr/local/spack/opt/spack/linux-debian12-x86_64/gcc-12.2.0/r-stringi-1.7.12-mdhexbolfliwhef2n3rcbvobz5nzoqmv/rlib/R/library")
library(rlang)
library(Seurat)
library(ggplot2)
library(data.table)
library(tidyverse)
library(RColorBrewer)
library(devtools)
library(SourceFromGithub)
library("plyr")
library(dplyr)
library(stringi)
library(conflicted)
library(ggplotify)
library(print.rmd.tabs)
conflict_prefer(name = "intersect", winner = "base")
conflict_prefer(name = "select", winner = "dplyr")
conflict_prefer(name = "filter", winner = "dplyr")
conflict_prefer(name = "mutate", winner = "dplyr")
conflict_prefer(name = "arrange", winner = "dplyr")
conflicts_prefer(dplyr::rename)
conflicts_prefer(dplyr::summarize)
conflicts_prefer(magrittr::set_names)
conflicts_prefer(dplyr::desc)
library(rmarkdown)


