# Generated by MakefileR, do not edit by hand

.Phony: all

all: pre_process cell_types immune_identity starCAT Tcells_types caf_subtypes umap_clustering cancer_pathway_analysis run_liana_per_patient Liana_per_patient nichenet_analysis TPM_for_signature_matrix create_dou_matrix create_ferrarotto_matrix create_brayer_matrix Dou_CIBERSORT_analysis ferrarotto_CIBERSORT_analysis Brayer_CIBERSORT_analysis sipsic_run sipsic_analysis

# ============
# pre_process
# ============

pre_process: ./Reports/01_pre-process/01_pre-process.html ./Reports/01_pre-process/acc_immune.RDS
	@echo  $@ is up to date

./Reports/01_pre-process/01_pre-process.html ./Reports/01_pre-process/acc_immune.RDS &: ./Notebooks/01_pre-process.Rmd ./input_data/raw_counts/Feb24_1 ./input_data/raw_counts/Feb24_2 ./input_data/raw_counts/SN0276364 ./input_data/raw_counts/SN0276892 ./input_data/raw_counts/GSE210171_acc_scrnaseq_counts.txt
	Rscript render.R pre_process

# ============
# cell_types
# ============

cell_types: ./Reports/02_cell_type_assignment/02_cell_type_assignment.html ./Reports/02_cell_type_assignment/immune.RDS ./Reports/02_cell_type_assignment/cancer.RDS ./Reports/02_cell_type_assignment/acc_cancer_pri.RDS ./Reports/02_cell_type_assignment/caf.RDS
	@echo  $@ is up to date

./Reports/02_cell_type_assignment/02_cell_type_assignment.html ./Reports/02_cell_type_assignment/immune.RDS ./Reports/02_cell_type_assignment/cancer.RDS ./Reports/02_cell_type_assignment/acc_cancer_pri.RDS ./Reports/02_cell_type_assignment/caf.RDS &: ./Notebooks/02_cell_type_assignment.Rmd ./Reports/01_pre-process/acc_immune.RDS input_data/oncotarget-05-12528-s001_acchigh.txt
	Rscript render.R cell_types

# ============
# immune_identity
# ============

immune_identity: ./Reports/03_immune_cell_types/03_immune_cell_types.html ./Reports/03_immune_cell_types/immune_with_cell_types.RDS ./Reports/03_immune_cell_types/starCAT_input/matrix.mtx.gz ./Reports/03_immune_cell_types/starCAT_input/barcodes.tsv.gz ./Reports/03_immune_cell_types/starCAT_input/features.tsv.gz
	@echo  $@ is up to date

./Reports/03_immune_cell_types/03_immune_cell_types.html ./Reports/03_immune_cell_types/immune_with_cell_types.RDS ./Reports/03_immune_cell_types/starCAT_input/matrix.mtx.gz ./Reports/03_immune_cell_types/starCAT_input/barcodes.tsv.gz ./Reports/03_immune_cell_types/starCAT_input/features.tsv.gz &: ./Notebooks/03_immune_cell_types.Rmd ./Reports/02_cell_type_assignment/immune.RDS
	Rscript render.R immune_identity

# ============
# starCAT
# ============

starCAT: ./Reports/04_starCAT/ACC.rf_usage_normalized.txt ./Reports/04_starCAT/ACC.scores.txt
	@echo  $@ is up to date

./Reports/04_starCAT/ACC.rf_usage_normalized.txt ./Reports/04_starCAT/ACC.scores.txt: ./Reports/03_immune_cell_types/starCAT_input/matrix.mtx.gz
	mkdir -p ./Reports/04_starCAT; starcat --reference "TCAT.V1" --counts ./Reports/03_immune_cell_types/starCAT_input/matrix.mtx.gz --output-dir ./Reports/04_starCAT --name "ACC"

# ============
# Tcells_types
# ============

Tcells_types: ./Reports/04_Tcells_types/04_Tcells_types.html ./Reports/04_Tcells_types/t_cells_labled.RDS ./Reports/04_Tcells_types/immune_with_Tcells.RDS
	@echo  $@ is up to date

./Reports/04_Tcells_types/04_Tcells_types.html ./Reports/04_Tcells_types/t_cells_labled.RDS ./Reports/04_Tcells_types/immune_with_Tcells.RDS &: ./Notebooks/04_Tcells_types.Rmd ./Reports/03_immune_cell_types/immune_with_cell_types.RDS ./Reports/04_starCAT/ACC.rf_usage_normalized.txt ./Reports/04_starCAT/ACC.scores.txt
	Rscript render.R Tcells_types

# ============
# caf_subtypes
# ============

caf_subtypes: ./Reports/CAF_subtypes/CAF_subtypes.html ./Reports/CAF_subtypes/caf_with_subtypes.RDS
	@echo  $@ is up to date

./Reports/CAF_subtypes/CAF_subtypes.html ./Reports/CAF_subtypes/caf_with_subtypes.RDS &: ./Notebooks/CAF_subtypes.Rmd ./Reports/02_cell_type_assignment/caf.RDS ./input_data/NIHMS1678398-supplement-2.xlsx
	Rscript render.R caf_subtypes

# ============
# umap_clustering
# ============

umap_clustering: ./Reports/05_UMAP_clustering/05_UMAP_clustering.html
	@echo  $@ is up to date

./Reports/05_UMAP_clustering/05_UMAP_clustering.html &: ./Notebooks/05_UMAP_clustering.Rmd ./Reports/01_pre-process/acc_immune.RDS ./Reports/03_immune_cell_types/immune_with_cell_types.RDS ./Reports/04_Tcells_types/t_cells_labled.RDS ./Reports/CAF_subtypes/caf_with_subtypes.RDS ./input_data/NIHMS1678398-supplement-2.xlsx
	Rscript render.R umap_clustering

# ============
# cancer_pathway_analysis
# ============

cancer_pathway_analysis: ./Reports/06_immune_markers_ACC/06_immune_markers_ACC.html ./Reports/06_immune_markers_ACC/signif_deg.rds
	@echo  $@ is up to date

./Reports/06_immune_markers_ACC/06_immune_markers_ACC.html ./Reports/06_immune_markers_ACC/signif_deg.rds &: ./Notebooks/06_immune_markers_ACC.Rmd ./Reports/02_cell_type_assignment/acc_cancer_pri.RDS input_data/all_direct_and_indirect_annotations_to_GO_immune_system_process.txt
	Rscript render.R cancer_pathway_analysis

# ============
# run_liana_per_patient
# ============

run_liana_per_patient: Reports/ccc_analysis/run_LIANA_per_patient/run_LIANA_per_patient.html Reports/ccc_analysis/run_LIANA_per_patient/liana_result_CD45-caf.RDS Reports/ccc_analysis/run_LIANA_per_patient/liana_result_CD45-cancer.RDS Reports/ccc_analysis/run_LIANA_per_patient/liana_result_CD45-lum-myo.RDS
	@echo  $@ is up to date

Reports/ccc_analysis/run_LIANA_per_patient/run_LIANA_per_patient.html Reports/ccc_analysis/run_LIANA_per_patient/liana_result_CD45-caf.RDS Reports/ccc_analysis/run_LIANA_per_patient/liana_result_CD45-cancer.RDS Reports/ccc_analysis/run_LIANA_per_patient/liana_result_CD45-lum-myo.RDS &: ./Notebooks/ccc_analysis/run_LIANA_per_patient.Rmd ./Reports/04_Tcells_types/t_cells_labled.RDS ./Reports/02_cell_type_assignment/cancer.RDS ./Reports/CAF_subtypes/caf_with_subtypes.RDS ./Reports/03_immune_cell_types/immune_with_cell_types.RDS
	Rscript render.R run_liana_per_patient

# ============
# Liana_per_patient
# ============

Liana_per_patient: Reports/ccc_analysis/LIANA_per_patient/LIANA_per_patient.html
	@echo  $@ is up to date

Reports/ccc_analysis/LIANA_per_patient/LIANA_per_patient.html &: ./Notebooks/ccc_analysis/LIANA_per_patient.Rmd Reports/ccc_analysis/run_LIANA_per_patient/liana_result_CD45-caf.RDS Reports/ccc_analysis/run_LIANA_per_patient/liana_result_CD45-cancer.RDS Reports/ccc_analysis/run_LIANA_per_patient/liana_result_CD45-lum-myo.RDS
	Rscript render.R Liana_per_patient

# ============
# nichenet_analysis
# ============

nichenet_analysis: Reports/ccc_analysis/Nichenet_analysis/Nichenet_analysis.html
	@echo  $@ is up to date

Reports/ccc_analysis/Nichenet_analysis/Nichenet_analysis.html &: ./Notebooks/ccc_analysis/Nichenet_analysis.Rmd ./Reports/04_Tcells_types/t_cells_labled.RDS ./Reports/02_cell_type_assignment/cancer.RDS ./Reports/CAF_subtypes/caf_with_subtypes.RDS ./Reports/03_immune_cell_types/immune_with_cell_types.RDS Reports/ccc_analysis/run_LIANA_per_patient/liana_result_CD45-caf.RDS Reports/ccc_analysis/run_LIANA_per_patient/liana_result_CD45-cancer.RDS Reports/ccc_analysis/run_LIANA_per_patient/liana_result_CD45-lum-myo.RDS
	Rscript render.R nichenet_analysis

# ============
# TPM_for_signature_matrix
# ============

TPM_for_signature_matrix: Reports/Bulk_deconv/Creat_TPM_matrix_for_csx_signature/Creat_TPM_matrix_for_csx_signature.html Reports/Bulk_deconv/Creat_TPM_matrix_for_csx_signature/acc_tpm_for_signature_matrix.txt
	@echo  $@ is up to date

Reports/Bulk_deconv/Creat_TPM_matrix_for_csx_signature/Creat_TPM_matrix_for_csx_signature.html Reports/Bulk_deconv/Creat_TPM_matrix_for_csx_signature/acc_tpm_for_signature_matrix.txt &: ./Notebooks/Bulk_deconv/Creat_TPM_matrix_for_csx_signature.Rmd ./Reports/04_Tcells_types/t_cells_labled.RDS ./Reports/02_cell_type_assignment/cancer.RDS ./Reports/02_cell_type_assignment/caf.RDS ./Reports/03_immune_cell_types/immune_with_cell_types.RDS
	Rscript render.R TPM_for_signature_matrix

# ============
# create_dou_matrix
# ============

create_dou_matrix: Reports/Bulk_deconv/create_dou_matrix/dou_exprs.tsv Reports/Bulk_deconv/create_dou_matrix/create_dou_matrix.html
	@echo  $@ is up to date

Reports/Bulk_deconv/create_dou_matrix/dou_exprs.tsv Reports/Bulk_deconv/create_dou_matrix/create_dou_matrix.html &: ./Notebooks/Bulk_deconv/create_dou_matrix.Rmd input_data/Dou_PMC8450584/PMC8450584_DataSheet_1.xlsx input_data/Dou_PMC8450584/PMC8450584_DataSheet_2.xlsx
	Rscript render.R create_dou_matrix

# ============
# create_ferrarotto_matrix
# ============

create_ferrarotto_matrix: Reports/Bulk_deconv/create_ferrarotto_matrix/ferrarotto_TPM.tsv Reports/Bulk_deconv/create_ferrarotto_matrix/Create_ferrarotto_TPM.html
	@echo  $@ is up to date

Reports/Bulk_deconv/create_ferrarotto_matrix/ferrarotto_TPM.tsv Reports/Bulk_deconv/create_ferrarotto_matrix/Create_ferrarotto_TPM.html &: ./Notebooks/Bulk_deconv/Create_Ferrarotto_TPM.Rmd input_data/Ferrarotto_PMC7854509/ACC_RNAseq_PMC7854509_RPKM.xlsx
	Rscript render.R create_ferrarotto_matrix

# ============
# create_brayer_matrix
# ============

create_brayer_matrix: Reports/Bulk_deconv/create_brayer_matrix/brayer_TPM.tsv Reports/Bulk_deconv/create_brayer_matrix/Create_brayer_TPM.html
	@echo  $@ is up to date

Reports/Bulk_deconv/create_brayer_matrix/brayer_TPM.tsv Reports/Bulk_deconv/create_brayer_matrix/Create_brayer_TPM.html &: ./Notebooks/Bulk_deconv/create_Brayer_TPM.Rmd input_data/Brayer_PMC10000625_and_PMC5800907/TX_All_Genes_Data.csv input_data/Brayer_PMC10000625_and_PMC5800907/DK_All_Genes_Data.csv
	Rscript render.R create_brayer_matrix

# ============
# Dou_CIBERSORT_analysis
# ============

Dou_CIBERSORT_analysis: Reports/Bulk_deconv/Dou_CIBERSORT_analsyis/Dou_CIBERSORT_analsyis.html
	@echo  $@ is up to date

Reports/Bulk_deconv/Dou_CIBERSORT_analsyis/Dou_CIBERSORT_analsyis.html &: ./Notebooks/Bulk_deconv/Dou_CIBERSORT_analsyis.Rmd input_data/Dou_PMC8450584/PMC8450584_DataSheet_2.xlsx input_data/CIBERSORTx_result/CIBERSORTx_Job23_Results_dou_all_10Kvargenes_relative_bBatchcorrection.csv
	Rscript render.R Dou_CIBERSORT_analysis

# ============
# ferrarotto_CIBERSORT_analysis
# ============

ferrarotto_CIBERSORT_analysis: Reports/Bulk_deconv/ferrarotto_CIBERSORT_analysis/ferrarotto_CIBERSORT_analysis.html
	@echo  $@ is up to date

Reports/Bulk_deconv/ferrarotto_CIBERSORT_analysis/ferrarotto_CIBERSORT_analysis.html &: ./Notebooks/Bulk_deconv/Ferrarotto_CIBERSORT_analsyis.Rmd ./input_data/CIBERSORTx_result/CIBERSORTx_Job30_Results.csv input_data/Ferrarotto_PMC7854509/CCR2020_Clinical.xlsx
	Rscript render.R ferrarotto_CIBERSORT_analysis

# ============
# Brayer_CIBERSORT_analysis
# ============

Brayer_CIBERSORT_analysis: Reports/Bulk_deconv/brayer_CIBERSORT_analsyis/brayer_CIBERSORT_analsyis.html
	@echo  $@ is up to date

Reports/Bulk_deconv/brayer_CIBERSORT_analsyis/brayer_CIBERSORT_analsyis.html &: ./Notebooks/Bulk_deconv/Brayer_CIBERSORT_analysis.Rmd ./input_data/Brayer_PMC10000625_and_PMC5800907/DK_sample_data_table2.csv ./input_data/Brayer_PMC10000625_and_PMC5800907/TX_sample_data_table2.csv input_data/CIBERSORTx_result/CIBERSORTx_Job28_Results_brayer_10Kvargenes_relative_bBatchCorrection.csv
	Rscript render.R Brayer_CIBERSORT_analysis

# ============
# sipsic_run
# ============

sipsic_run: Reports/Pathway_analysis/09_sipsic_run/09_sipsic_run.html Reports/Pathway_analysis/09_sipsic_run/sipsic_matrix.RDS
	@echo  $@ is up to date

Reports/Pathway_analysis/09_sipsic_run/09_sipsic_run.html Reports/Pathway_analysis/09_sipsic_run/sipsic_matrix.RDS &: ./Notebooks/Pathway_analysis/09_sipsic_run.Rmd ./Reports/02_cell_type_assignment/acc_cancer_pri.RDS ./input_data/h.all.v2025.1.Hs.symbols.gmt
	Rscript render.R sipsic_run

# ============
# sipsic_analysis
# ============

sipsic_analysis: Reports/Pathway_analysis/10_sipsic_analysis/10_sipsic_analysis.html
	@echo  $@ is up to date

Reports/Pathway_analysis/10_sipsic_analysis/10_sipsic_analysis.html &: ./Notebooks/Pathway_analysis/10_sipsic_analysis.qmd ./Reports/02_cell_type_assignment/acc_cancer_pri.RDS Reports/Pathway_analysis/09_sipsic_run/sipsic_matrix.RDS
	Rscript render.R sipsic_analysis
