---
title: 'cpbd_analysis' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
---
```{r}
library(stringi)
library(Seurat)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(data.table)
library(print.rmd.tabs)
library(knitr)
library(ktplots)

```


```{r}
source("./pipe.R")
input = pipeline$cpdb_analysis_per_patient$input
output = pipeline$cpdb_analysis_per_patient$output
```

```{r}
acc_cancer_Tcells_caf = readRDS(input$acc_cancer_Tcells_caf)

```

```{r}
my_plot_cpdb <- function(...,caf = F) {
  p = plot_cpdb(...)
  pg <- ggplot_build(p)
  
  ## switch all to ligand-receptor:
  # p_pairs = pg$plot$data$Var1 %>% gsub(pattern = "-",replacement = "_")
  # pval_cut = pvals %>%  column_to_rownames(var = "interacting_pair")  
  # pval_cut = pval_cut[p_pairs,c("receptor_a","receptor_b","gene_a","gene_b","partner_a","partner_b")]
  # 
  # pg$plot$data = cbind(pg$plot$data, pval_cut)
  # rows_to_switch = pg$plot$data$receptor_a == "False" & pg$plot$data$receptor_b == "True"
  # a = apply(pg$plot$data[169:179,], MARGIN = 1, switch_genes) 

  # add facet
  if (caf == F){
    pg$plot$data  %<>%  mutate(lum_or_myo = if_else(condition = grepl(pattern = "Luminal",x = Var2),
                                                    true = "Luminal",false = "Myo"))%>% 
      mutate(direction =if_else(condition = grepl(pattern = "-Luminal|-Myo",x = Var2),
                                    true = "immune->cancer" ,false = "cancer->immune")) 
      pg$plot+facet_grid(cols = vars(direction,lum_or_myo),scales = "free_x")+ylab("Interacting pair") +
      theme(axis.title.y = element_text(angle = 90,size = 20))
      
  }else{
    pg$plot$data  %<>%  mutate(direction =if_else(condition = grepl(pattern = "-.*CAF",x = Var2),true = "immune->CAF",false = "CAF->immune")) 
      pg$plot+facet_grid(cols = vars(direction),scales = "free_x")+ylab("Interacting pair") +
      theme(axis.title.y = element_text(angle = 90,size = 20))
  }
}
```


```{r}
all_pvals = list()
all_means = list()
for (patient in c("ACC22", "ACC15", "ACC7",  "ACC5")) {
  seurat_data = dirname(input$create_data_report) %s+% "/cells_seurat_" %s+% patient %s+% ".RDS"
  pvals = dirname(input$run_cpdb_per_patient_report) %s+% "/cpdb_out/statistical_analysis_pvalues_" %s+% patient %s+% ".txt"
  means = dirname(input$run_cpdb_per_patient_report) %s+% "/cpdb_out/statistical_analysis_means_" %s+% patient %s+% ".txt"
  all_pvals[[patient]] = fread(pvals)
  all_means[[patient]] = fread(means) %>% as.data.frame()
}
```

```{r}
all_cols_list = list()
all_rows_list = list()
all_significant_interactions =list()
for (patient in names(all_pvals)) {
  just_pvals = all_pvals[[patient]][,12:ncol(all_pvals[[patient]])] %>% as.matrix()
  rownames(just_pvals) = all_pvals[[patient]]$id_cp_interaction
  colnames(just_pvals) = colnames(all_pvals[[patient]][,12:ncol(all_pvals[[patient]])])
  
  
  results = just_pvals < 0.05 
  significant_indexes = which(results,arr.ind = TRUE) %>% as.data.frame()
  all_significant_interactions[[patient]] = paste(rownames(results)[significant_indexes$row], colnames(results)[significant_indexes$col],sep = "~")


}


all_significant_interactions_accum = Reduce(intersect, all_significant_interactions,accumulate = T)
min_patients = 3 #include interactions that in least this patients

all_significant_interactions_min_patients = all_significant_interactions_accum[[min_patients]]
SplitCoords <- strsplit(all_significant_interactions_min_patients, split = "~") 
all_common_cols = unique(sapply(SplitCoords, `[`, 2))
all_common_pairs = unique(sapply(SplitCoords, `[`, 1))

all_common_pvals = matrix(1, nrow = length(all_common_pairs), ncol = length(all_common_cols),
                          dimnames = list(all_common_pairs, all_common_cols)) %>% as.data.frame()


for (interaction in all_significant_interactions_min_patients) {
  result_indices <- sapply(all_significant_interactions_accum, function(vec) {
    return(interaction %in% vec)
  })
  
  interacting_pair = strsplit(interaction,split = "~")[[1]][1]
  interacting_cells = strsplit(interaction,split = "~")[[1]][2]
  all_common_pvals[interacting_pair, interacting_cells] <- 10^-max(which(result_indices))
}


all_common_pvals$id_cp_interaction = rownames(all_common_pvals)

average_means = matrix(0, nrow = length(all_common_pairs), ncol = length(all_common_cols),
                          dimnames = list(all_common_pairs, all_common_cols)) %>% as.data.frame()

for (interaction in SplitCoords) {
  all_means_for_interaction = c()
  for (means_df in all_means) {
    all_means_for_interaction = c(all_means_for_interaction,means_df[means_df$id_cp_interaction ==interaction[1],interaction[2]])
  }
  
  average_means[interaction[1],interaction[2]] <- mean(all_means_for_interaction)
  
}

average_means$id_cp_interaction = rownames(average_means)


```





```{r}
average_means = right_join(all_means[[1]][,1:11],average_means,by = "id_cp_interaction") %>% as.data.frame()
all_common_pvals = right_join(all_means[[1]][,1:11],all_common_pvals,by = "id_cp_interaction") %>% as.data.frame()

```

```{r fig.height=10, fig.width=10}
p = my_plot_cpdb(cell_type1 = 'CD|Treg|gdT', cell_type2 = 'Luminal pri|Myo pri', scdata = acc_cancer_Tcells_caf,
                      idents = 'cell_type', means = average_means, pvals = all_common_pvals,
                      gene.family = NULL,return_table = F,max_size = 3,p.adjust.method = NULL,
                      keep_significant_only = T,cluster_rows = T,scale = F,highlight = c("green","red"),highlight_size = 2)+
  labs(color = "Significant in patients")
p
```
```{r}
pdf(file = params$data_out_dir %s+% "Common cancer-Tcells interactions in patients.pdf",width = 12,height = 10)
p
dev.off()

```
```{r fig.height=13, fig.width=20}
p = my_plot_cpdb(cell_type1 = 'CD|Treg|gdT', cell_type2 = 'CAF', scdata = acc_cancer_Tcells_caf,caf = T,
                      idents = 'cell_type', means = average_means, pvals = all_common_pvals,
                      gene.family = NULL,return_table = F,max_size = 3,p.adjust.method = NULL,
                      keep_significant_only = T,cluster_rows = T,scale = F,highlight = c("green","red"),highlight_size = 2)+
  labs(color = "Significant in patients")
p
```

