---
title: 'Pre process' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
---
```{r}
library(stringi)
library(Seurat)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(data.table)
library(print.rmd.tabs)
library(Matrix)
```


```{r}
source("./pipe.R")
input = pipeline$pre_process$input
output = pipeline$pre_process$output
```


# Functions

```{r warning=FALSE}
tpm <- function(counts, lengths) {
  rpk <- counts / lengths
  coef <- sum(rpk) / 1e6
  rpk/coef
}

rpk <- function(counts, lengths) {
  rpk <- counts / lengths
  rpk
}
```

# Read data
```{r}
acc_immune_data_part1 <- fread(input$SN0276364,
      skip = 0,
      header = TRUE,
      sep = "\t",
      stringsAsFactors = FALSE,
      data.table = FALSE, # To get a data.frame output similar to read.delim
      check.names = FALSE) %>% column_to_rownames("Geneid")

acc_immune_data_part2 <- fread(input$SN0276892,
      skip = 0,
      header = TRUE,
      sep = "\t",
      stringsAsFactors = FALSE,
      data.table = FALSE, # To get a data.frame output similar to read.delim
      check.names = FALSE) %>% column_to_rownames("Geneid")

acc_immune_data_part3 <- fread(input$feb24_1,
      skip = 0,
      header = TRUE,
      sep = "\t",
      stringsAsFactors = FALSE,
      data.table = FALSE, # To get a data.frame output similar to read.delim
      check.names = FALSE) %>% column_to_rownames("Geneid")

acc_immune_data_part4 <- fread(input$feb24_2,
      skip = 0,
      header = TRUE,
      sep = "\t",
      stringsAsFactors = FALSE,
      data.table = FALSE, # To get a data.frame output similar to read.delim
      check.names = FALSE) %>% column_to_rownames("Geneid")

acc_cancer <- fread(input$acc_cancer,
      skip = 0,
      header = TRUE,
      sep = "\t",
      stringsAsFactors = FALSE,
      data.table = FALSE, # To get a data.frame output similar to read.delim
      check.names = FALSE) %>% column_to_rownames("Geneid")
```

# Pre-process
```{r}
# remove version number any  ".3" in ENGS***.3 :
acc_genes_no_version = gsub(pattern = "\\..*$" ,replacement = "",x = rownames(acc_cancer)) 
rownames(acc_cancer) = make.unique(acc_genes_no_version)

#find common genens between datasets
all_common_genes = Reduce(intersect, 
                          list(rownames(acc_immune_data_part1),
                               rownames(acc_immune_data_part2),                
                               rownames(acc_immune_data_part3),
                               rownames(acc_immune_data_part4),
                               acc_genes_no_version))
#save length and symbols
genes_lengths = acc_immune_data_part1[all_common_genes,5]
gene_symbols = acc_immune_data_part1[, "gene_name",drop=F]
gene_symbols$gene_name = make.unique(gene_symbols$gene_name)

#omit non relevant cols
acc_immune_data_part1=acc_immune_data_part1[,7:ncol(acc_immune_data_part1)]
acc_immune_data_part2=acc_immune_data_part2[,7:ncol(acc_immune_data_part2)]
acc_immune_data_part3=acc_immune_data_part3[,7:ncol(acc_immune_data_part3)]
acc_immune_data_part4=acc_immune_data_part4[,7:ncol(acc_immune_data_part4)]
acc_cancer=acc_cancer[,6:ncol(acc_cancer)]



#set colnames for immune
colnames(acc_immune_data_part1) <- gsub(pattern = "/.*$",replacement = "",colnames(acc_immune_data_part1)) %>%
  gsub(pattern = "_",replacement = "-")
colnames(acc_immune_data_part2) <- gsub(pattern = "/.*$",replacement = "",colnames(acc_immune_data_part2))%>%
  gsub(pattern = "_",replacement = "-")
colnames(acc_immune_data_part3) <- gsub(pattern = "/.*$",replacement = "",colnames(acc_immune_data_part3))%>%
  gsub(pattern = "_",replacement = "-")
colnames(acc_immune_data_part4) <- gsub(pattern = "/.*$",replacement = "",colnames(acc_immune_data_part4))%>%
  gsub(pattern = "_",replacement = "-")

#set colnames for acc
cell.labels <- gsub(".gene_counts.tsv","",colnames(acc_cancer))
cell.labels <- gsub(".sort.bam","",cell.labels)
cell.labels <- gsub("_",".",cell.labels)
cell.labels <- gsub(".S[0-9]*","",cell.labels)
cell.labels <- gsub("\\.","-",cell.labels)
colnames(acc_cancer) = cell.labels


# save sequencing info
seq_origin = rbind(
  data.frame(cell_name = colnames(acc_immune_data_part1),origin = "immune_6364"),
  data.frame(cell_name = colnames(acc_immune_data_part2),origin = "immune_6892"),
  data.frame(cell_name = colnames(acc_immune_data_part3),origin = "immune_feb24_1"),
  data.frame(cell_name = colnames(acc_immune_data_part4),origin = "immune_feb24_2"),
  data.frame(cell_name = colnames(acc_cancer),origin = "acc_data"))
seq_origin  = seq_origin %>% column_to_rownames("cell_name")

#combine datasets
acc_immune_data = cbind(
  acc_immune_data_part1[all_common_genes, ],
  acc_immune_data_part2[all_common_genes, ],
  acc_immune_data_part3[all_common_genes, ],
  acc_immune_data_part4[all_common_genes, ],
  acc_cancer[all_common_genes, ]
)

#add gene stmbol to data
acc_immune_data = left_join(rownames_to_column(acc_immune_data),y = rownames_to_column(gene_symbols)
          ,by = c("rowname" = "rowname"))
acc_immune_data = acc_immune_data %>%  column_to_rownames("gene_name")
acc_immune_data$rowname = NULL



#calcualte gene length and MT genes
mt_genes = startsWith(rownames(acc_immune_data),"MT-")| startsWith(rownames(acc_immune_data),"ERCC-")



# make seurat object 
acc_immune_counts <- CreateSeuratObject(counts = acc_immune_data, project = "acc_immune_counts", min.cells = 3, min.features = 1000)
acc_immune_counts = AddMetaData(object = acc_immune_counts,metadata = seq_origin)
```

# QC  {.tabset}
```{r echo=TRUE, results='asis'}
acc_immune_counts@meta.data[["percent.mt"]] <- PercentageFeatureSet(acc_immune_counts, pattern = "^MT-")
print_tab(plt = 
            FeatureScatter(acc_immune_counts, feature1 = "nCount_RNA", feature2 = "percent.mt") + 
            theme(legend.position="none", axis.text.x = element_text(size=8)) + 
              geom_point(color='darkblue')
  
            ,title = "MT percentages")

print_tab(plt = 
            VlnPlot(acc_immune_counts, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3,group.by = "origin")
,title = "violin plots")

```


```{r}
# store TPM values as counts
acc_immune_data.tpm=apply(acc_immune_data[!mt_genes,], 2, function(x) tpm(x, genes_lengths[!mt_genes]))
acc_immune <- CreateSeuratObject(counts = acc_immune_data.tpm, project = "acc_immune", min.cells = 3, min.features = 1000)
acc_immune = AddMetaData(object = acc_immune,metadata = seq_origin)

```

```{r}
#store log2(tpm+1) as data slot
acc_immune@assays$RNA@data = Matrix(log2(acc_immune@assays$RNA@counts+1),sparse = T) 

#take relevant data from counts 
acc_immune$nCount_RNA = acc_immune_counts$nCount_RNA
acc_immune$nFeature_RNA = acc_immune_counts$nFeature_RNA
acc_immune$percent.mt = acc_immune_counts$percent.mt
```



# Filtering
```{r}
nFeature_RNA_threshold = 1000
percent.mt_threshold = 40
print ("nFeature_RNA threshold = " %>% paste(nFeature_RNA_threshold))
print ("percent.mt threshold = " %>% paste(percent.mt_threshold))

acc_immune <- subset(acc_immune, subset = nFeature_RNA > nFeature_RNA_threshold & percent.mt < percent.mt_threshold)
acc_immune
```

```{r}
VlnPlot(acc_immune, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

# PCA
```{r results='hide'}
# Identification of highly variable features
acc_immune <- FindVariableFeatures(acc_immune, selection.method = "vst", nfeatures = 15000) 

# Scaling the data
acc_immune <- ScaleData(acc_immune, vars.to.regress = c("percent.mt","nCount_RNA"),features = VariableFeatures(object = acc_immune))

# Perform linear dimensional reduction (PCA)
acc_immune <- RunPCA(acc_immune, features = VariableFeatures(object = acc_immune))

ElbowPlot(acc_immune, ndims = 50) # checking the dimensionality 
```

```{r}
pc2use=1:10
clus_res=1
```

# UMAP and clustering
```{r}
acc_immune <- FindNeighbors(acc_immune, dims = pc2use,verbose = F)
acc_immune <- FindClusters(acc_immune, resolution = clus_res,verbose = F)

# Run non-linear dimensional reduction (UMAP)
acc_immune <- RunUMAP(acc_immune, dims = pc2use,verbose = F)
DimPlot(object = acc_immune, reduction = "umap", pt.size = 1, label = F)
```


# metadata
```{r}


acc_cell_names = colnames(acc_immune) %>% as.data.frame()

acc_cell_names$patient.ident = str_extract(colnames(acc_immune), "ACC[0-9]*") %>% as.factor()
acc_cell_names$plate <- sub("-[A-Z][0-9]+$", "", acc_cell_names[,1])%>% as.factor() #remove cell name to get plate 

ln_plates_in_acc_data = c("ACC22-LN-P11", "ACC22-P12-LN", "ACC5-P11",  "ACC7-P13")
ln_plates_in_immune_data = c("ACC7-P18","ACC7-P19-LN","ACC22-P18-LN", "ACC22-P19-LN", "ACC7-LN-P20")
all_ln_plates = c(ln_plates_in_acc_data, ln_plates_in_immune_data)

acc_cell_names$tissue = ifelse(test = acc_cell_names$plate %in% all_ln_plates, yes =  "LN", no = "pri") %>% as.factor()
acc_cell_names = acc_cell_names %>% column_to_rownames(".")

# no ACC7_P18 
acc_immune <- AddMetaData(object = acc_immune, metadata = acc_cell_names[,"patient.ident",drop=F], col.name = "patient.ident")
acc_immune <- AddMetaData(object = acc_immune, metadata = acc_cell_names[,"plate",drop=F], col.name = "plate")
acc_immune <- AddMetaData(object = acc_immune, metadata = acc_cell_names[,"tissue",drop=F], col.name = "tissue")
```

# UMAPS {.tabset}

```{r echo=TRUE, results='asis'}
print_tab(DimPlot(object = acc_immune, reduction = "umap", pt.size = 1, label = F,group.by = "origin"),title = "origin")
print_tab(DimPlot(object = acc_immune, reduction = "umap", pt.size = 1, label = F,group.by = "patient.ident"),title = "patient.ident")
print_tab(DimPlot(object = acc_immune, reduction = "umap", pt.size = 1, label = F,group.by = "tissue"),title = "tissue")
```



```{r}
saveRDS(object = acc_immune,file = params$data_out_dir %s+% basename(output$acc_immune))
```

