---
title: 'Cell types' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
---
```{r}
library(stringi)
library(Seurat)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(data.table)
library(print.rmd.tabs)
library(Matrix)
```

```{r}
source("./pipe.R")
input = pipeline$immune_identity$input
output = pipeline$immune_identity$output
```

# Functions

```{r warning=FALSE}

scAssign_db <- function(tissue) {
  lapply(c("dplyr","Seurat","HGNChelper"), library, character.only = T)
  source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/gene_sets_prepare.R"); source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/sctype_score_.R")
  
  db_ = "https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/ScTypeDB_full.xlsx";
  tissue = tissue # e.g. Immune system,Pancreas,Liver,Eye,Kidney,Brain,Lung,Adrenal,Heart,Intestine,Muscle,Placenta,Spleen,Stomach,Thymus 
  
  # prepare gene sets
  gs_list = gene_sets_prepare(db_, tissue)
  
  # add treg  genes from: https://panglaodb.se/markers.html?cell_type=%27T%20regulatory%20cells%27
  
  return(gs_list)
}

scAssign <- function(seuratObj,gs_list, metadata_name = "cell_identity") {
  es.max = sctype_score(scRNAseqData = seuratObj[["RNA"]]@scale.data, scaled = TRUE, 
                      gs = gs_list$gs_positive, gs2 = gs_list$gs_negative) 
  # merge by cluster
  cL_resutls = do.call("rbind", lapply(unique(seuratObj@meta.data$seurat_clusters), function(cl){
      es.max.cl = sort(rowSums(es.max[ ,rownames(seuratObj@meta.data[seuratObj@meta.data$seurat_clusters==cl, ])]), decreasing = !0)
      head(data.frame(cluster = cl, type = names(es.max.cl), scores = es.max.cl, ncells = sum(seuratObj@meta.data$seurat_clusters==cl)), 10)
  }))
  print(cL_resutls)
  sctype_scores = cL_resutls %>% group_by(cluster) %>% top_n(n = 1, wt = scores)  
  
  # set low-confident (low ScType score) clusters to "unknown"
  sctype_scores$type[as.numeric(as.character(sctype_scores$scores)) < sctype_scores$ncells/4] = "Unknown"

  seuratObj@meta.data[[metadata_name]] = ""
  for(j in unique(sctype_scores$cluster)){
    cl_type = sctype_scores[sctype_scores$cluster==j,]; 
    seuratObj@meta.data[[metadata_name]][seuratObj@meta.data$seurat_clusters == j] = as.character(cl_type$type[1])
  }
  return(seuratObj)
}

```

```{r}
immune = readRDS(input$immune)

```

```{r}
immune = FindClusters(object = immune,resolution = 1)

DimPlot(immune)
```


```{r echo=TRUE, results='asis'}
gs_list = scAssign_db(tissue = "Immune system")
immune = immune %>%  scAssign(gs_list = gs_list,metadata_name = "immune_type")
immune$immune_type = immune$immune_type %>% gsub(patter = " cells",replacement = "") #remove "cells"
```

```{r echo=TRUE, fig.height=6, fig.width=9, results='asis'}
immune %<>%  SetIdent(value = "immune_type")
print_tab(DimPlot(immune,group.by = "immune_type",label = T),title = "UMAP")
FeaturePlot(immune,features = c("CD8A"))
print_tab(plt = immune$immune_type %>% table() %>% as.data.frame(), title = "cell count")
```


```{r}
table(immune@meta.data[,c("origin","immune_type")])
```


```{r}
saveRDS(object = immune,file = params$data_out_dir %s+% basename(output$immune_with_cell_types))
```

# write input for starCAT

```{r}
t_cells_types = c("Naive CD4+ T", "Effector CD8+ T", "CD8+ NKT-like")
t_cells = immune[,immune$immune_type %in% t_cells_types]
```

```{r}
counts = t_cells@assays$RNA@data #SUPPOSE TO BE COUNTS!! when 3' seq, this is smart seq (full lenght), q asked in starCAT github
data_dir = "starCAT_input/"
dir.create(params$data_out_dir %s+% data_dir, recursive = TRUE)

# Output counts matrix
writeMM(counts, paste0(params$data_out_dir,data_dir, 'matrix.mtx'))
system(paste0("gzip ",params$data_out_dir,data_dir, 'matrix.mtx'))

# Output cell barcodes
barcodes <- colnames(counts)
write_delim(as.data.frame(barcodes), paste0(params$data_out_dir,data_dir, 'barcodes.tsv'),
           col_names = FALSE)
system(paste0("gzip ",params$data_out_dir,data_dir, 'barcodes.tsv'))

# Output feature names
gene_names <- rownames(counts)
features <- data.frame("gene_id" = gene_names,"gene_name" = gene_names,type = "Gene Expression")
write_delim(as.data.frame(features),delim = "\t", paste0(params$data_out_dir,data_dir, 'features.tsv'),
           col_names = FALSE)
system(paste0("gzip ",params$data_out_dir,data_dir, 'features.tsv'))
```


