---
title: 'Cell types' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
---

```{r}
library(stringi)
library(Seurat)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(data.table)
library(print.rmd.tabs)
```

```{r setup}
if (interactive()) {
    setwd(here::here())
    params <- rmarkdown::yaml_front_matter(rstudioapi::getSourceEditorContext()$path)$params
}
```

```{r}
source("./pipe.R")
input = pipeline$umap_clustering$input
output = pipeline$umap_clustering$output
```

```{r}
acc_immune = readRDS(input$acc_immune)
immune_with_cell_types = readRDS(input$immune_with_cell_types)
acc_cancer_pri = readRDS(input$acc_cancer_pri)
t_cells_labled = readRDS(input$t_cells_labled)
caf_with_subtypes = readRDS(input$caf_with_subtypes)
```

# ACC+ immune UMAP
```{r}
new.cluster.ids2 <- c("0" ="cancer",
                      "1" = "immune",
                      "2" = "CAF",
                      "3" = "cancer",
                      "4" = "cancer",
                      "5" = "immune",
                      "6" = "CAF",
                      "7" = "cancer",
                      "8" = "CAF",
                      "9" = "immune",
                      "10" = "immune",
                      "11" = "endothelial",
                      "12" = "cancer",
                      "13" = "CAF",
                      "14" = "immune",
                      "15" = "cancer",
                      "16" = "immune",
                      "17" = "immune")              
names(new.cluster.ids2) <- levels(acc_immune$seurat_clusters)
acc_immune <- RenameIdents(acc_immune, new.cluster.ids2)
acc_immune = acc_immune %>% AddMetaData(metadata = acc_immune@active.ident,col.name = 'cell_identity')
```

```{r}
# add immune cell types to acc_immune
cell_identity = acc_immune@meta.data[, "cell_identity",drop=F]
immune_type = immune_with_cell_types@meta.data[, "immune_type",drop=F]
# merge by rownames using merge
merged_data = merge(cell_identity, immune_type, by = "row.names", all.x = TRUE) %>% column_to_rownames("Row.names") %>%
  mutate(cell_identity = if_else(condition = (cell_identity == "immune"), true = immune_type, false = cell_identity))

#rename T cells subtypes to T cells
merged_data$cell_identity = str_replace(merged_data$cell_identity, fixed("CD8+ NKT-like"), "T cells")
merged_data$cell_identity = str_replace(merged_data$cell_identity, fixed("Effector CD8+ T"), "T cells")
merged_data$cell_identity = str_replace(merged_data$cell_identity, fixed("Naive CD4+ T"), "T cells")
```

```{r}
acc_immune = acc_immune %>% AddMetaData(metadata = merged_data[,"cell_identity",drop=F],col.name = "cell_identity_with_subtypes")
```

```{r}
p = DimPlot(acc_immune,group.by = "cell_identity_with_subtypes",label = F,label.size = 5, pt.size = 4,raster = T, raster.dpi = c(2048 , 2048 ))+ scale_color_manual(values = rainbow(length(unique(acc_immune$cell_identity_with_subtypes)))) + ggtitle("Single-Cell Landscape of ACC Cohort") + theme(plot.title = element_text(hjust = 0.5),legend.text = element_text(size = 14),  
  axis.text = element_blank(),  # Removes all tick text labels
    axis.ticks = element_blank()  # Removes all tick marks
)

p_bold <- LabelClusters(plot = p, id = "cell_identity_with_subtypes", fontface = "bold", size = 5, repel = TRUE)
p_bold
```

```{r}
filename = "umap_all_cell_types.svg"
svglite::svglite(file.path(params$data_out_dir,filename), width = 12, height = 10)
print(p_bold)
dev.off()

compare_and_save_svg(filename, new_svg_dir = params$data_out_dir, old_svg_dir = "./Figures/Retreat")
```

## split to lum/myo, keep only pri cells

```{r}
acc_immune = acc_immune %>% AddMetaData(metadata = acc_cancer_pri@meta.data[rownames(acc_immune@meta.data), "cell_identity"], col.name = "lum_or_myo")

acc_immune@meta.data = acc_immune@meta.data %>% 
  mutate(cell_identity_with_subtypes = if_else(condition = cell_identity_with_subtypes == "cancer", true = lum_or_myo, false = cell_identity_with_subtypes)) 

acc_immune_filtered = subset(acc_immune, subset = cell_identity_with_subtypes != "mid")
acc_immune_filtered = subset(acc_immune_filtered, subset = tissue == "pri")


```

```{r}
# Identification of highly variable features
acc_immune_filtered <- FindVariableFeatures(acc_immune_filtered, selection.method = "vst", nfeatures = 15000) 

# Scaling the data
acc_immune_filtered <- ScaleData(acc_immune_filtered, vars.to.regress = c("percent.mt","nCount_RNA"),features = VariableFeatures(object = acc_immune_filtered))

# Perform linear dimensional reduction (PCA)
acc_immune_filtered <- RunPCA(acc_immune_filtered, features = VariableFeatures(object = acc_immune_filtered))
acc_immune_filtered <- RunUMAP(acc_immune_filtered, dims = 1:10,verbose = F)
```

```{r}
p = DimPlot(acc_immune_filtered,group.by = "cell_identity_with_subtypes",label = F,label.size = 5, pt.size = 4,raster = T, raster.dpi = c(2048 , 2048 ))+ scale_color_manual(values = rainbow(length(unique(acc_immune_filtered$cell_identity_with_subtypes)))) + ggtitle("Single-Cell Landscape of ACC Cohort") + theme(plot.title = element_text(hjust = 0.5),legend.text = element_text(size = 14),  
  axis.text = element_blank(),  # Removes all tick text labels
    axis.ticks = element_blank()  # Removes all tick marks
)

p_bold <- LabelClusters(plot = p, id = "cell_identity_with_subtypes", fontface = "bold", size = 5, repel = TRUE)
p_bold
```

```{r}
filename = "umap_all_cell_types_primary_lum_myo.svg"
svglite::svglite(file.path(params$data_out_dir,filename), width = 12, height = 10)
print(p_bold)
dev.off()

compare_and_save_svg(filename, new_svg_dir = params$data_out_dir, old_svg_dir = "./Figures/Retreat")
```

# Immune UMAP

```{r}
immune_with_cell_types@meta.data = immune_with_cell_types@meta.data %>%
  mutate(immune_type =
           case_when(
             immune_type %in% c("Naive CD4+ T", "Effector CD8+ T", "CD8+ NKT-like") ~ "T cells",
             TRUE ~ immune_type
           )
  )
```


```{r}
p = DimPlot(immune_with_cell_types ,group.by = "immune_type",cols =  rainbow(7)) 
p
```

```{r}
svg_filename <- "umap_immune_cells.svg"
svglite::svglite(file.path(params$data_out_dir, svg_filename), width = 12, height = 10)
print(p)
dev.off()

compare_and_save_svg(svg_filename,  new_svg_dir = params$data_out_dir)
```

# T
 cells UMAP
```{r}
library(RColorBrewer)
library(colorspace)
my_colors <- c(sequential_hcl(3, palette = "Blues", l = c(30, 70), c = c(80, 40))
  ,sequential_hcl(4, palette = "Greens", l = c(30, 70), c = c(80, 40))
  ,"red","hotpink1","gold1")

p = DimPlot(t_cells_labled,group.by = "t_cell_label",cols =  my_colors, pt.size = 3) 
p
```

```{r}
svg_filename <- "umap_with_t_cell_subtypes.svg"
svglite::svglite(file.path(params$data_out_dir, svg_filename), width = 12, height = 10)
print(p)
dev.off()

compare_and_save_svg(svg_filename, new_svg_dir = params$data_out_dir)
```

```{r fig.height=8, fig.width=12}
immune_plate_df = acc_immune[[c("plate","origin")]] %>% 
  mutate(immune_plate = if_else(condition = (origin == "acc_data"),true = "acc_old_data",false = plate))

acc_immune %<>% AddMetaData(metadata = immune_plate_df[,"immune_plate",drop=F])
DimPlot(object = acc_immune, reduction = "umap", pt.size = 0.3, label = F,group.by = "immune_plate",cols = rainbow(length(unique(acc_immune$immune_plate))))
```

```{r}
table(acc_immune$immune_plate)
```

```{r}
immune_plate_df = acc_immune@meta.data %>% select(seurat_clusters,immune_plate) %>% group_by(seurat_clusters) %>%dplyr::count(immune_plate)%>%
  ungroup()

ggplot(immune_plate_df, aes(x = seurat_clusters, y = n, fill = immune_plate)) +
  geom_bar(stat = "identity", position = "stack")+
  labs(
    title = "Immune Plate Composition per Seurat Cluster (Counts)",
    x = "Seurat Clusters",
    y = "Number of Cells",
    fill = "Immune Plate"
  ) +
  theme_minimal() + # רקע נקי יותר
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```


# CAF types dotplot

```{r}
library(readxl)
caf_signatures = read_excel(path = input$caf_signatures,sheet = 3,skip = 1)
caf_signatures = lapply(caf_signatures, na.omit)
names(caf_signatures) = names(caf_signatures) %>% gsub(pattern = "-",replacement = ".")
```

## UMAP
```{r}
DimPlot(object = caf_with_subtypes, reduction = "umap", pt.size = 1, label = T,group.by = "cell_identity")
```

## Violin plot of CAF subtypes scores
```{r}

#| fig-height: 10
#| fig-width: 13
p = VlnPlot(caf_with_subtypes,features = paste0(names(caf_signatures),"_score"),pt.size = 1,group.by = "cell_identity",cols = rainbow(length(unique
    (caf_with_subtypes$cell_identity))), same.y.lims = T) +
  DimPlot(caf_with_subtypes,group.by = "cell_identity", cols = rainbow(length(unique(caf_with_subtypes$cell_identity))))

p
```

```{r}
svg_filename <- "vlnplot_caf_subtypes_scores.svg"
svglite::svglite(file.path(params$data_out_dir, svg_filename), width = 12, height = 10)
p
dev.off()

compare_and_save_svg(svg_filename, new_svg_dir = params$data_out_dir)
```

