---
title: 'create_data_for_CIBERSORT' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
---
```{r}
library(stringi)
library(Seurat)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(data.table)
library(print.rmd.tabs)
```


```{r}
source("./pipe.R")
input = pipeline$create_data_for_CIBERSORT$input
output = pipeline$create_data_for_CIBERSORT$output
```




```{r}
acc_cancer_cells = readRDS(input$cancer)
acc_caf_cells =  readRDS(input$caf)
immune_with_Tcells = readRDS(input$immune_with_Tcells)
```


# Create TPM matrix
Create TPM matrix with cell type in col names , later upload to cibersort to create signature matrix from TPM using.
use genes that were identified as markers of the existing cell types 
use cancer cells +CAF + immune + T cells 


```{r}
#remove unclear lum-myo cells
acc_cancer_cells_no_mid = subset(acc_cancer_cells,subset = cell_identity != "mid")

# merge cancer, immune and CAF
common_genes = rownames(acc_cancer_cells_no_mid) %>% intersect (rownames(immune_with_Tcells)) %>% intersect(rownames(acc_caf_cells))
acc_cancer_and_cd45 = merge(acc_cancer_cells_no_mid[common_genes,],immune_with_Tcells[common_genes,])
overlapping_cells = colnames(acc_cancer_cells_no_mid) %>% intersect(colnames(acc_caf_cells)) 
acc_cancer_CD45_caf = merge(acc_cancer_and_cd45[common_genes,],acc_caf_cells[common_genes,] )
```

```{r}
# set common cell type metadata 
metadata = FetchData(acc_cancer_CD45_caf,vars = c("tissue","cell_identity","immune_type"))
metadata  = metadata %>%  mutate(cell_type = 
                                   if_else(condition = cell_identity == "immune",
                                           true = immune_type,
                                           false = cell_identity))
acc_cancer_CD45_caf = AddMetaData(object = acc_cancer_CD45_caf,metadata = metadata[,"cell_type",drop=F],col.name = "cell_type")

```


## Set markers
```{r}
#markers for sctype cell types
tissue = "Immune system"
library(HGNChelper)
source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/gene_sets_prepare.R"); source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/sctype_score_.R")

db_ = "https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/ScTypeDB_full.xlsx";
tissue = tissue # e.g. Immune system,Pancreas,Liver,Eye,Kidney,Brain,Lung,Adrenal,Heart,Intestine,Muscle,Placenta,Spleen,Stomach,Thymus 

# prepare gene sets
gs_list = gene_sets_prepare(db_, tissue)

#take only signature that found in data
sctype_signatures_in_data = gs_list$gs_positive [names(gs_list$gs_positive ) %in% 
                                                   unique(acc_cancer_CD45_caf$cell_type)]
signatures = sctype_signatures_in_data


```

```{r}
# acc cell types markers
myo_genes = c("TP63","TP73","CAV1","CDH3","KRT5","KRT14","ACTA2","TAGLN","MYLK","DKK3")
lum_genes = c("KIT","EHF","ELF5","KRT7","CLDN3","CLDN4","CD24","LGALS3","LCN2","SLPI")
signatures[["Myo"]] = c("TP63","TP73","CAV1","CDH3","KRT5","KRT14","ACTA2","TAGLN","MYLK","DKK3")
signatures[["Luminal"]] = c("KIT","EHF","ELF5","KRT7","CLDN3","CLDN4","CD24","LGALS3","LCN2","SLPI")
signatures[["CAF"]] = c("COL3A1","COL1A2")

```

```{r}
#CD45 markers from starCAT
library(readxl)
starCAT_top_genes = readxl::read_excel(,path = "./input_data/starCAT/starCAT_PMC11092745_Supplementary_Tables.xlsx", 
                   sheet = "S2 - cGEP Top Genes",skip = 2)

names(starCAT_top_genes) = gsub(x = names(starCAT_top_genes) ,pattern = "-",replacement = "_") #set valin names
names(starCAT_top_genes) = gsub(x = names(starCAT_top_genes) ,pattern = "/",replacement = ".") #set valin names

#take only signature that found in data
starCAT_top_genes = starCAT_top_genes[,colnames(starCAT_top_genes) %in% unique(immune_with_Tcells$immune_type)]
signatures = c(signatures,starCAT_top_genes %>% as.list())


```



```{r}
all_markers = unlist(signatures)[unlist(signatures) %in% rownames(immune_with_Tcells)] %>% unique()
```

## set matrix
```{r}
# get exprs
signature_matrix = acc_cancer_CD45_caf@assays$RNA@counts[all_markers,] %>% data.frame(check.names = F)
signature_matrix = signature_matrix %>%  rownames_to_column(var = "gene")
rownames(signature_matrix) = NULL

signature_matrix = signature_matrix %>% as.matrix()

#set colnames to be cell type (req for cibersort)
colnames(signature_matrix)[2:length(colnames(signature_matrix))] <- unname(acc_cancer_CD45_caf$cell_type)
```


```{r}
fwrite(x = signature_matrix,file = params$data_out_dir %s+% basename(output$tpm_matrix) ,sep = "\t",
       row.names = F, quote = FALSE)
```

# create Bulk RNA-seq data to be deconv
```{r}
dou_exprs = readxl::read_excel(input$dou_acc,sheet = 2,col_names = T,skip = 1) %>% as.data.frame()

```

```{r}
library(biomaRt)
#convert from ensmle to gene symbols 

ensembl <- useEnsembl(biomart = "genes", dataset = "hsapiens_gene_ensembl")

ensembl_ids <- dou_exprs$GeneID


mapped_genes <- getBM(
  attributes = c("ensembl_gene_id", "hgnc_symbol"),
  filters = "ensembl_gene_id",
  values = ensembl_ids,
  mart = ensembl
)
# Return the gene symbols (hgnc_symbol) in the original order of the Ensembl IDs, including NA for unmatched entries
mapped_ordered <- mapped_genes$hgnc_symbol[match(ensembl_ids, mapped_genes$ensembl_gene_id)]


dou_exprs$gene_symbol = mapped_ordered
dou_exprs= dou_exprs %>% na.omit()
rownames(dou_exprs) = dou_exprs$gene_symbol %>% make.unique()
dou_exprs$GeneID <- NULL
dou_exprs$gene_symbol <- NULL
```


```{r}

dou_exprs$`P-50`<- NULL # almost all 0 expression
colnames(dou_exprs)  = colnames(dou_exprs) %>% gsub(replacement = "_",pattern = "-") # cibersort don't accept "-"
```

```{r}
fwrite(dou_exprs,file = params$data_out_dir %s+% basename(output$dou_exprs), sep = "\t",row.names = T)
```



