---
title: 'Dou_CIBERSORT_analysis' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
---
```{r}
library(stringi)
library(Seurat)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(data.table)
library(print.rmd.tabs)
library(grid)
library(ComplexHeatmap)
```

```{r}
source("./pipe.R")
input = pipeline$Dou_CIBERSORT_analysis$input
output = pipeline$Dou_CIBERSORT_analysis$output
```


```{r}
dou_survival = readxl::read_excel(input$dou_acc_survival,sheet = 1,col_names = T,skip = 1) %>% as.data.frame()
```


```{r}
deconv_result = fread(input$cs_result)
deconv_result
```

```{r}
dou_survival= dou_survival[dou_survival$"Case Number" != "P-50",]

```

# Histopathology- lum/myo ratio 
```{r}

df = data.frame(lum_ratio = deconv_result$Luminal/(deconv_result$Luminal + deconv_result$Myo) ,
                  Histopathology = dou_survival$Histopathology)

# Convert all text to lowercase (or use str_to_title() for capitalized)
df$Histopathology <- tolower(df$Histopathology)

# Remove leading and trailing whitespace
df$Histopathology <- trimws(df$Histopathology)

# Replace multiple spaces (or other whitespace) with a single space
df$Histopathology <- gsub("[[:space:]]+", " ", df$Histopathology)
df$Histopathology <- gsub("mixed， solid component<30%", "mixed, solid component<30%", df$Histopathology)


```

```{r}
library(dplyr)
library(ggplot2)

# Step 1: summary per category
df_summary <- df %>%
  group_by(Histopathology) %>%
  dplyr::summarise(
    mean_ratio = mean(lum_ratio[is.finite(lum_ratio)]),
    .groups = "drop"
  )

# Step 2: barplot with discrete fill
ggplot(df_summary, aes(x = reorder(Histopathology, -mean_ratio), y = mean_ratio)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_fill_brewer(palette = "Blues", direction = 1) +  # discrete color scale
  labs(
    x = "Histopathology",
    y = "Mean lum_ratio",
  ) +
  theme_minimal()

```

# Treshold

```{r}
ratio_threshold = 0.5
df <- df %>%
  mutate(
    LumCategory = ifelse(lum_ratio > ratio_threshold, paste("High (>",ratio_threshold,")"), paste("Low (<=",ratio_threshold,")"))
  )

my_colors <- c(
  "solid" = "red",
  "mixed cribriform-solid type" = "pink",
  "mixed, solid component<30%" = "coral1",
  "mixed" = "orange",
  "cribriform" = "blue",
  "tubular" = "deepskyblue",
  "mix of tubular and cribriform" = "cyan",
  "unknown" = "grey",
  "adenoid cystic carcinoma ex pleomorphic adenomas" = "black"
)

df$Histopathology <- factor(df$Histopathology, levels = c(
names(my_colors)
))


ggplot(df, aes(x = LumCategory, fill = Histopathology)) +
  geom_bar(position = "fill") +  
  labs(
    title = "Distribution of Histopathology by Luminal Ratio Category",
    x = "Luminal Ratio Category",
    y = "Proportion"
  ) +
  scale_fill_manual(values = my_colors) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


# immune inflatration correlation
```{r}
# T cells ratio
deconv_result_with_survival = deconv_result %>% as.data.frame()
deconv_result_with_survival = deconv_result_with_survival %>% 
  select(-c("Mixture", "P-value", "Correlation","RMSE"))
t_cells_names = c( "CD8_Naive", "CD4_Naive", "CD8_CM", "CD4_CM", "CD4_EM", "CD8_EM", "gdT",
                   "Treg", "CD8_TEMRA","MAIT")
deconv_result_with_survival$t_cells_ratio = rowSums(deconv_result_with_survival[, colnames(deconv_result_with_survival) %in% t_cells_names])

# Immune cells ratio
immune_cells_names = c( "Naive B", "CD8_Naive", "CD4_Naive", 
"CD8_CM", "CD4_CM", "CD4_EM", "CD8_EM", "Plasmacytoid Dendritic", 
"gdT", "Treg", "CD8_TEMRA", "Macrophages", "Basophils", "Neutrophils", 
"MAIT", "Plasma B", "Myeloid Dendritic")
deconv_result_with_survival$immune_cells_ratio = rowSums(deconv_result_with_survival[, colnames(deconv_result_with_survival) %in% immune_cells_names])

deconv_result_with_survival$lum_ratio = deconv_result_with_survival$Luminal/(deconv_result_with_survival$Luminal + deconv_result_with_survival$Myo)

deconv_result_with_survival$myo_ratio = deconv_result_with_survival$Myo/(deconv_result_with_survival$Luminal + deconv_result_with_survival$Myo)


deconv_result_with_survival$`Immune infiltration score (IIS)` = dou_survival$`Immune infiltration score (IIS)`
deconv_result_with_survival$`T cell infiltration score (TIS)` = dou_survival$`T cell infiltration score (TIS)`
deconv_result_with_survival["Antigen presenting machinery (APM)"] = dou_survival["Antigen presenting machinery (APM)"]
deconv_result_with_survival["Antigen presenting machinery (APM)"] = dou_survival["Antigen presenting machinery (APM)"]
deconv_result_with_survival["indel_TMB"] = dou_survival["indel_TMB"]
deconv_result_with_survival["Tumour mutational burden (TMB)"] = dou_survival["Tumour mutational burden (TMB)"]
"Tumour mutational burden (TMB)"
deconv_result_with_survival["indel_TMB"] = dou_survival["indel_TMB"]
deconv_result_with_survival["Locoregional recurrence-free survival (LRRFS)"] = dou_survival["Locoregional recurrence-free survival (LRRFS)"]
deconv_result_with_survival["Distant metastasis-free survival time (DMFS)" ] = dou_survival["Distant metastasis-free survival time (DMFS)" ]



correlation_matrix <- cor(
  x = deconv_result_with_survival[,1:24],
  y = deconv_result_with_survival[,25:length(deconv_result_with_survival)],
  method = "pearson" 
)
all_pairs = expand.grid(
  Item_A = rownames(correlation_matrix), 
  Item_B = colnames(correlation_matrix)
)


p_values_vector = apply(all_pairs, MARGIN = 1, FUN = function(x){
  pair_a = x[[1]]
  pair_b = x[[2]]
  p_val = cor.test(deconv_result_with_survival[[pair_a]], deconv_result_with_survival[[pair_b]])[["p.value"]]
    }
) %>% p.adjust(method = "fdr")

all_pvals = matrix(
  p_values_vector,
  nrow = nrow(correlation_matrix),
  ncol = ncol(correlation_matrix)
) %>% as.data.frame()
rownames(all_pvals) = rownames(correlation_matrix)
colnames(all_pvals) = colnames(correlation_matrix)


```


```{r}
convert <- function(vec) {
  symnum(vec, corr = FALSE, na = FALSE, cutpoints = c(0, 
    0.001, 0.01, 0.05, 0.1, 1), symbols = c("***", "**", "*", ".", " ")) %>% as.character()
} 
all_pvals[] = apply(all_pvals, MARGIN = 2, FUN = convert)
```

```{r fig.height=8, fig.width=15}


col_fun = circlize::colorRamp2(c(-1, 0, 1), c("royalblue4", "white", "red"))
p = ComplexHeatmap::Heatmap(t(correlation_matrix),  row_names_gp = gpar(fontsize = 8), 
                            name = "Pearson",
                            clustering_method_rows = "average",show_heatmap_legend = T,col = col_fun, 
                            clustering_distance_rows = "euclidean", 
                            cell_fun = function(j, i, x, y, width, height, fill) {
                              grid.text(t(all_pvals)[i, j], x, y, gp = gpar(fontsize = 8))
                              },
                            column_names_rot =45,column_title = "cell types %",column_title_side = "bottom",
                            row_title = "patient data", row_title_side = "right"
    
)

p
```

```{r}
cell_type = "CD8_TEMRA"
data = data.frame(fraction = deconv_result[[cell_type]],
                  TIS = dou_survival$`T cell infiltration score (TIS)`)

library(ggplot2)
library(ggpubr) 
# יצירת גרף הפיזור הבסיסי
p <- ggplot(data, aes(x = fraction, y = TIS)) +
  geom_point() + # הוספת נקודות הפיזור
  labs(title = "cell type vs. score",
       x = paste (cell_type, "fraction"),
       y = "T cell infiltration score") +
  theme_minimal()+ # רקע נקי יותר +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`, `~")),
           label.x = 0.04, label.y = 0.62) 
p
```

# cell types- survival
```{r}
cell_type = "Myo"
data = data.frame(fraction = deconv_result[[cell_type]],
                  survival = dou_survival$`Locoregional recurrence-free survival (LRRFS)`)

library(ggplot2)
library(ggpubr) 
# יצירת גרף הפיזור הבסיסי
p <- ggplot(data, aes(x = fraction, y = survival)) +
  geom_point() + # הוספת נקודות הפיזור
  labs(title = "Survival vs. Fraction",
       x = paste (cell_type, "Fraction"),
       y = "recurrence-free survival") +
  theme_minimal()+ # רקע נקי יותר +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`, `~")),
           label.x = 0.4, label.y = 130) 
p
```

```{r}
cell_type = "Luminal"
data = data.frame(fraction = deconv_result[[cell_type]],
                  survival = dou_survival$`Locoregional recurrence-free survival (LRRFS)`)

library(ggplot2)
library(ggpubr) 
# יצירת גרף הפיזור הבסיסי
p <- ggplot(data, aes(x = fraction, y = survival)) +
  geom_point() + # הוספת נקודות הפיזור
  labs(title = "Survival vs. Fraction",
       x = paste (cell_type, "Fraction"),
       y = "recurrence-free survival") +
  theme_minimal()+ # רקע נקי יותר +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`, `~")),
           label.x = 0.4, label.y = 130) 
p
```
```{r}
cell_type = "CD8_TEMRA"
data = data.frame(fraction = deconv_result[[cell_type]],
                  survival =dou_survival$`Locoregional recurrence-free survival (LRRFS)`)

library(ggplot2)
library(ggpubr) 
# יצירת גרף הפיזור הבסיסי
p <- ggplot(data, aes(x = fraction, y = survival)) +
  geom_point() + # הוספת נקודות הפיזור
  labs(title = "Survival vs. Fraction",
       x = paste (cell_type, "Fraction"),
       y = "recurrence-free survival") +
  theme_minimal()+ # רקע נקי יותר +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`, `~")),
           label.x = 0.05, label.y = 130) + ggtitle(cell_type) 
p
```

```{r}
cell_type = "CAF"
data = data.frame(fraction = deconv_result[[cell_type]],
                  survival =dou_survival$`Locoregional recurrence-free survival (LRRFS)`)

library(ggplot2)
library(ggpubr) 
# יצירת גרף הפיזור הבסיסי
p <- ggplot(data, aes(x = fraction, y = survival)) +
  geom_point() + # הוספת נקודות הפיזור
  labs(title = "Survival vs. Fraction",
       x = paste (cell_type, "Fraction"),
       y = "recurrence-free survival") +
  theme_minimal()+ # רקע נקי יותר +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`, `~")),
           label.x = 0.02, label.y = 130) + ggtitle(cell_type) 
p
```


```{r}

 
 cell_type = "Treg"
data = data.frame(fraction = deconv_result[[cell_type]],
                  survival =dou_survival$`Locoregional recurrence-free survival (LRRFS)`)

library(ggplot2)
library(ggpubr) 
# יצירת גרף הפיזור הבסיסי
p <- ggplot(data, aes(x = fraction, y = survival)) +
  geom_point() + # הוספת נקודות הפיזור
  labs(title = "Survival vs. Fraction",
       x = paste (cell_type, "Fraction"),
       y = "recurrence-free survival") +
  theme_minimal()+ # רקע נקי יותר +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`, `~")),
           label.x = 0.01, label.y = 130) + ggtitle(cell_type) 
p
```
