---
title: 'CAF subtypes' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/"
  assign_threshold: 1.0
  var_genes: 15000
  calculate_from: "scale.data" #scale.data or data
---

```{r}
library(stringi)
library(Seurat)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(data.table)
library(print.rmd.tabs)
library(readxl)
library(cowplot)
library(ComplexHeatmap)
library(circlize)
library(grid)
library(patchwork)

```

```{r setup}
if(Sys.getenv("POSITRON") == "1"){
    setwd(here::here())
    params <- rmarkdown::yaml_front_matter(rstudioapi::getSourceEditorContext()$path)$params
}
```

```{r}
source("./pipe.R")
input = pipeline$caf_subtypes$input
output = pipeline$caf_subtypes$output
```

# read CAF

```{r}
caf = readRDS(input$caf)
caf_signatures = read_excel(path = input$caf_signatures,sheet = 3,skip = 1)

caf_signatures = lapply(caf_signatures, na.omit)
names(caf_signatures) = names(caf_signatures) %>% gsub(pattern = "-",replacement = ".")
```

# Scale data

```{r}
# Identification of highly variable features
caf <- FindVariableFeatures(caf, selection.method = "vst", nfeatures = params$var_genes) 
variable_genes = VariableFeatures(caf)
# Scaling the data
caf <- ScaleData(caf, vars.to.regress = c("percent.mt","nCount_RNA"),features = VariableFeatures(object = caf))
```

# Dim reduction

```{r results='hide'}

# Perform linear dimensional reduction (PCA)
caf <- RunPCA(caf, features = VariableFeatures(object = caf))

ElbowPlot(caf, ndims = 50) # checking the dimensionality 
```

```{r}
pc2use = 10
resolution = 0.4
caf <- FindNeighbors(caf, dims = 1:pc2use,verbose = F,annoy.metric = "cosine")
caf <- FindClusters(caf, resolution = resolution, verbose = F)

# Run non-linear dimensional reduction (UMAP)
caf <- RunUMAP(caf, dims = 1:pc2use,verbose = F)


```

```{r}
DimPlot(caf,group.by = "patient.ident", cols = rainbow(length(unique(caf$patient.ident)))) +
DimPlot(caf,group.by = "seurat_clusters", cols = rainbow(length(unique(caf$seurat_clusters))))

```

# Calculate mean score

```{r}


#calculate CAF scores mean expression of signature genes
for (signature_name in names(caf_signatures)) {
  signature_genes = caf_signatures[[signature_name]]
  signature_genes = signature_genes[signature_genes %in% rownames(caf)]
  signature_genes = intersect(signature_genes, variable_genes) # limit to variable genes
  if (length(signature_genes) == 0) {
    warning(paste0("No signature genes found for ",signature_name))
    next
  }
  if (params$calculate_from == "scale.data") {
    caf_score = caf@assays$RNA@scale.data[signature_genes,] %>% colMeans()
  } else if (params$calculate_from == "data") {
    caf_score = caf@assays$RNA@data[signature_genes,] %>% colMeans()
  } else {
    stop("Invalid value for params$calculate_from. Must be 'scale.data' or 'data'")
  }
  caf = AddMetaData(object =caf,metadata = caf_score,col.name = paste0(signature_name,"_score"))
}

```

# Caf idents with max score

```{r}

data = FetchData(caf,vars = paste0(names(caf_signatures),"_score"))

#get max signature per cell
data$Max_signature <- apply(
  data, 
  MARGIN = 1, 
  FUN = function(x) {
    max_value = max(x)
    second_max_value = sort(x, decreasing = TRUE)[2]
    if (max_value > second_max_value*params$assign_threshold) {
      return(names(x)[which.max(x)])
    } else {
      return("Mixed")
    }
  }
)

#remove _score
data$Max_signature = gsub("_score", "", data$Max_signature)
#add to metadata
caf = AddMetaData(object =caf,metadata = data[,"Max_signature",drop=F],col.name = "cell_identity")
```

```{r}
table(caf$cell_identity)
```



```{r}
#| fig-height: 10
#| fig-width: 15
VlnPlot(caf,features = paste0(names(caf_signatures),"_score"),pt.size = 1,group.by = "seurat_clusters",cols = rainbow(length(unique
    (caf$seurat_clusters))), same.y.lims = T) +
  DimPlot(caf,group.by = "seurat_clusters", cols = rainbow(length(unique(caf$seurat_clusters))))


```

```{r}
caf = SetIdent(object = caf, value = "cell_identity")
```

```{r}
#| fig-height: 15
#| fig-width: 20
colors = rainbow(length(unique(caf$cell_identity)))
colors[[2]] = "gold1"
colors[[3]] = "darkgreen"
library(RColorBrewer)
p1 = VlnPlot(caf,features = paste0(names(caf_signatures),"_score"),pt.size = 1,group.by = "cell_identity",
  cols = colors, same.y.lims = T) &
      theme(axis.text.x = element_text(size = 17))


p2 = DimPlot(caf,group.by = "cell_identity", cols = colors, pt.size =2) + 
# increse legend size
 theme(legend.text = element_text(size = 17), legend.title = element_text(size = 14)) + 
  guides(color = guide_legend(override.aes = list(size = 5))) # increase legend point size

p1 + p2 
```

```{r}
#| fig-height: 10
#| fig-width: 15
VlnPlot(caf,features = paste0(names(caf_signatures),"_score"),pt.size = 1,group.by = "cell_identity",cols = rainbow(length(unique
    (caf$cell_identity))), same.y.lims = T) +
  DimPlot(caf,group.by = "cell_identity", cols = rainbow(length(unique(caf$cell_identity))))


```


```{r}
# combine dCAF and pCAF into one group
caf@meta.data$cell_identity = caf@meta.data$cell_identity %>% gsub(pattern = "pan.dCAF|pan.pCAF",replacement = "dCAF/pCAF")
table(caf@meta.data$cell_identity )
```

```{r}
#| fig-height: 10
#| fig-width: 15
VlnPlot(caf,features = paste0(names(caf_signatures),"_score"),pt.size = 1,group.by = "cell_identity",cols = rainbow(length(unique
    (caf$cell_identity))), same.y.lims = T) +
  DimPlot(caf,group.by = "cell_identity", cols = rainbow(length(unique(caf$cell_identity))))


```


```{r}
caf = SetIdent(object = caf, value = "seurat_clusters")

```





```{r}
FeaturePlot(caf,features = paste0(names(caf_signatures),"_score"),pt.size = 2) + plot_layout(ncol = 3)

```

```{r}
#| fig-height: 10
#| fig-width: 15
VlnPlot(caf,features = paste0(names(caf_signatures),"_score"),pt.size = 1,group.by = "seurat_clusters",cols = rainbow(length(unique
    (caf$seurat_clusters))), same.y.lims = T) +
  DimPlot(caf,group.by = "seurat_clusters", cols = rainbow(length(unique(caf$seurat_clusters))))


```

```{r}
table(caf$cell_identity,caf$seurat_clusters)
```

```{r}
saveRDS(object = caf,file = params$data_out_dir %s+% basename(output$caf))
```

# SISPIC

see analysis in previous commnits