---
title: "R Notebook"
output: html_notebook
---


```{r}
tissue = "Immune system"

lapply(c("dplyr","Seurat","HGNChelper"), library, character.only = T)
source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/gene_sets_prepare.R"); source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/sctype_score_.R")

db_ = "https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/ScTypeDB_full.xlsx";
tissue = tissue # e.g. Immune system,Pancreas,Liver,Eye,Kidney,Brain,Lung,Adrenal,Heart,Intestine,Muscle,Placenta,Spleen,Stomach,Thymus 

# prepare gene sets
gs_list = gene_sets_prepare(db_, tissue)
  
  myo_genes = c("TP63","TP73","CAV1","CDH3","KRT5","KRT14","ACTA2","TAGLN","MYLK","DKK3")
lum_genes = c("KIT","EHF","ELF5","KRT7","CLDN3","CLDN4","CD24","LGALS3","LCN2","SLPI")
```

```{r}

signatures = gs_list$gs_positive 
signatures[["Myo"]] = c("TP63","TP73","CAV1","CDH3","KRT5","KRT14","ACTA2","TAGLN","MYLK","DKK3")
signatures[["Luminal"]] = c("KIT","EHF","ELF5","KRT7","CLDN3","CLDN4","CD24","LGALS3","LCN2","SLPI")

```

```{r}
acc_cancer_cd45_caf = readRDS("Reports/05_cellphoneDB/01_create_data_for_cellphoneDB/acc_cancer_cd45_caf.RDS")
```

```{r}
acc_cancer_cd45_caf$cell_type_no_env = gsub(x = acc_cancer_cd45_caf$cell_type,pattern = " pri",replacement = "")
acc_cancer_cd45_caf$cell_type_no_env = gsub(x = acc_cancer_cd45_caf$cell_type_no_env,pattern = " LN",replacement = "")
table(acc_cancer_cd45_caf$cell_type_no_env )
acc_cancer_cd45_caf = SetIdent(acc_cancer_cd45_caf,value = "cell_type_no_env")
signature_matrix = AverageExpression(object = acc_cancer_cd45_caf,features = unlist(signatures))[["RNA"]] %>% as.data.frame()
signature_matrix
```
```{r}
fwrite(x = signature_matrix,file = "signature_matrix.tsv",sep = "\t",row.names = T)
```

