---
title: 'Create data' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
---

```{r}
source("./pipe.R")
input = pipeline$cpdb_create_data_per_patient$input
output = pipeline$cpdb_create_data_per_patient$output
```

```{r}
library(ggplot2)
library(ggpubr)
library(stringi)
library(Seurat)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(data.table)
library(ComplexHeatmap)
library(readxl)

```


```{r}
acc_cancer_cells = readRDS(input$cancer)
acc_caf_cells =  readRDS(input$caf)
t_cells_labled =  readRDS(input$t_cells_labled)
immune_with_cell_types = readRDS(input$immune_with_cell_types)
```

```{r}
all_immune_meta = FetchData(immune_with_cell_types, vars = c("immune_type"))%>%
  mutate(immune_type = if_else(   #convert some T cell types to general T_cell label

  condition = immune_type %in% c("CD8+ NKT-like", "Naive CD4+ T", "Effector CD8+ T"),
  true = "T_cell",
  false = immune_type
))

immune_with_cell_types = AddMetaData(object = immune_with_cell_types,metadata = all_immune_meta[,"immune_type",drop=F],col.name = "immune_type")
```

```{r fig.height=6, fig.width=8}
DimPlot(immune_with_cell_types, reduction = "umap", group.by = "immune_type",pt.size = 1,label = T,repel  = T)
```


# Add CAF signatures

```{r}


caf_signatures = read_excel(path = input$caf_signatures,sheet = 3,skip = 1) 
caf_signatures = lapply(caf_signatures, na.omit)
names(caf_signatures) = names(caf_signatures) %>% gsub(pattern = "-",replacement = ".")

#calculate CAF scores mean expression of signature genes
for (signature_name in names(caf_signatures)) {
  signature_genes = caf_signatures[[signature_name]]
  signature_genes = signature_genes[signature_genes %in% rownames(acc_caf_cells)]
  caf_score = acc_caf_cells@assays$RNA@data[signature_genes,] %>% colMeans()
  acc_caf_cells = AddMetaData(object =acc_caf_cells,metadata = caf_score,col.name = signature_name)
}

data = FetchData(acc_caf_cells,vars = names(caf_signatures))

#get max signature per cell
data$Max_signature <- apply(
  data, 
  MARGIN = 1, 
  FUN = function(x) {
    max_index <- which.max(x)
    return(names(x)[max_index]) 
  }
)
#add to metadata
acc_caf_cells = AddMetaData(object =acc_caf_cells,metadata = data[,"Max_signature",drop=F],col.name = "cell_identity")

```

# write data for cellphoneDB per patient - T cells subtypes
```{r}
patients_with_t_cells = unique(t_cells_labled$patient.ident)
for (patient_name in patients_with_t_cells) {
  print(patient_name)
  patient_acc_data = subset(acc_cancer_cells,subset = patient.ident == patient_name)
  patient_caf_data = subset(acc_caf_cells,subset = patient.ident == patient_name)
  patient_t_cells_data = subset(t_cells_labled,subset = patient.ident == patient_name)
  
  #remove unclear lum-myo cells
  patient_acc_data_no_mid = subset(patient_acc_data,subset = cell_identity != "mid")
  
  # merge cancer, immune and CAF
  common_genes = rownames(patient_acc_data_no_mid) %>% intersect (rownames(patient_t_cells_data)) %>% intersect(rownames(patient_caf_data))
  acc_cancer_and_cd45 = merge(patient_acc_data_no_mid[common_genes,],patient_t_cells_data[common_genes,])
  overlapping_cells = colnames(patient_acc_data_no_mid) %>% intersect(colnames(patient_caf_data)) 
  acc_cancer_Tcells_caf = merge(acc_cancer_and_cd45[common_genes,],patient_caf_data[common_genes,] )
  
  #metadata
  metadata = FetchData(acc_cancer_Tcells_caf,vars = c("tissue","cell_identity","t_cell_label"))
  metadata  = metadata %>%  mutate(cell_type = 
                                     if_else(condition = cell_identity == "immune",
                                             true = paste(t_cell_label,tissue),
                                             false = paste(cell_identity, tissue)))
  acc_cancer_Tcells_caf = AddMetaData(object = acc_cancer_Tcells_caf,metadata = metadata[,"cell_type",drop=F],col.name = "cell_type")
  all_identity = data.frame(barcode_sample = rownames(metadata), cell_type = metadata$cell_type)
  all_environment = data.frame(cell_type = metadata$cell_type, microenviroment = metadata$tissue)
  
  
  #write
  dir.create(paste0(params$data_out_dir,"/T_subtypes/"),showWarnings = F)
  cells_identity_path = paste0(params$data_out_dir,"/T_subtypes/cells_identity_",patient_name,".tsv")
  cells_environment_path = paste0(params$data_out_dir,"/T_subtypes/cells_environment_",patient_name,".tsv")
  cells_counts_path = paste0(params$data_out_dir,"/T_subtypes/cells_counts_",patient_name,".txt")

  write.table(x = all_identity,file = cells_identity_path,row.names =F,sep = "\t")
  write.table(x = all_environment,file = cells_environment_path,row.names =F,sep = "\t")
  fwrite(as.data.frame(acc_cancer_Tcells_caf@assays[["RNA"]]@data), file = cells_counts_path,sep = "\t",row.names = T)
}
```

# write data for cellphoneDB per patient - all immune cells
```{r}
patients = unique(immune_with_cell_types$patient.ident)
for (patient_name in patients) {
  print(patient_name)
  patient_acc_data = subset(acc_cancer_cells,subset = patient.ident == patient_name)
  patient_caf_data = subset(acc_caf_cells,subset = patient.ident == patient_name)
  patient_immune_data = subset(immune_with_cell_types,subset = patient.ident == patient_name)
  
  #remove unclear lum-myo cells
  patient_acc_data_no_mid = subset(patient_acc_data,subset = cell_identity != "mid")
  
  # merge cancer, immune and CAF
  common_genes = rownames(patient_acc_data_no_mid) %>% intersect (rownames(patient_immune_data)) %>% intersect(rownames(patient_caf_data))
  acc_cancer_and_cd45 = merge(patient_acc_data_no_mid[common_genes,],patient_immune_data[common_genes,])
  overlapping_cells = colnames(patient_acc_data_no_mid) %>% intersect(colnames(patient_caf_data)) 
  acc_cancer_immune_caf = merge(acc_cancer_and_cd45[common_genes,],patient_caf_data[common_genes,] )
  
  #metadata
  metadata = FetchData(acc_cancer_immune_caf,vars = c("tissue","cell_identity","immune_type"))
  metadata  = metadata %>%  mutate(cell_type = 
                                     if_else(condition = cell_identity == "immune",
                                             true = paste(immune_type,tissue),
                                             false = paste(cell_identity, tissue)))
  acc_cancer_immune_caf = AddMetaData(object = acc_cancer_immune_caf,metadata = metadata[,"cell_type",drop=F],col.name = "cell_type")
  all_identity = data.frame(barcode_sample = rownames(metadata), cell_type = metadata$cell_type)
  all_environment = data.frame(cell_type = metadata$cell_type, microenviroment = metadata$tissue)
  
  
  #write
  dir.create(paste0(params$data_out_dir,"/all_immune/"),showWarnings = F)
  cells_identity_path = paste0(params$data_out_dir,"/all_immune/cells_identity_",patient_name,".tsv")
  cells_environment_path = paste0(params$data_out_dir,"/all_immune/cells_environment_",patient_name,".tsv")
  cells_counts_path = paste0(params$data_out_dir,"/all_immune/cells_counts_",patient_name,".txt")

  write.table(x = all_identity,file = cells_identity_path,row.names =F,sep = "\t")
  write.table(x = all_environment,file = cells_environment_path,row.names =F,sep = "\t")
  fwrite(as.data.frame(acc_cancer_immune_caf@assays[["RNA"]]@data), file = cells_counts_path,sep = "\t",row.names = T)
}
```

# create all patients data- all immune subtypes
```{r}


#remove unclear lum-myo cells
acc_cancer_cells_no_mid = subset(acc_cancer_cells,subset = cell_identity != "mid")

# merge cancer, immune and CAF
common_genes = rownames(acc_cancer_cells_no_mid) %>% intersect (rownames(immune_with_cell_types)) %>% intersect(rownames(acc_caf_cells))
acc_cancer_and_cd45 = merge(acc_cancer_cells_no_mid[common_genes,],immune_with_cell_types[common_genes,])
overlapping_cells = colnames(acc_cancer_cells_no_mid) %>% intersect(colnames(acc_caf_cells)) 
acc_cancer_immune_caf = merge(acc_cancer_and_cd45[common_genes,],acc_caf_cells[common_genes,] )
```

```{r}
metadata = FetchData(acc_cancer_immune_caf,vars = c("tissue","cell_identity","immune_type"))

metadata  = metadata %>%  mutate(cell_type =
                                   if_else(
                                     condition = cell_identity == "immune",
                                     true = paste(immune_type, tissue),
                                     false = paste(cell_identity, tissue)))


acc_cancer_immune_caf = AddMetaData(object = acc_cancer_immune_caf,metadata = metadata[,"cell_type",drop=F],col.name = "cell_type")

```

```{r}
saveRDS(acc_cancer_immune_caf,file = paste0(params$data_out_dir, basename(output$acc_cancer_immune_caf)))
```

# create all patients data- T cell subtypes

```{r}

#remove unclear lum-myo cells
acc_cancer_cells_no_mid = subset(acc_cancer_cells,subset = cell_identity != "mid")

# merge cancer, immune and CAF
common_genes = rownames(acc_cancer_cells_no_mid) %>% intersect (rownames(t_cells_labled)) %>% intersect(rownames(acc_caf_cells))
acc_cancer_and_cd45 = merge(acc_cancer_cells_no_mid[common_genes,],t_cells_labled[common_genes,])
overlapping_cells = colnames(acc_cancer_cells_no_mid) %>% intersect(colnames(acc_caf_cells)) 
acc_cancer_Tcells_caf = merge(acc_cancer_and_cd45[common_genes,],acc_caf_cells[common_genes,] )
```

```{r}
metadata = FetchData(acc_cancer_Tcells_caf,vars = c("tissue","cell_identity","t_cell_label"))
metadata  = metadata %>%  mutate(cell_type = 
                                   if_else(condition = cell_identity == "immune",
                                           true = paste(t_cell_label,tissue),
                                           false = paste(cell_identity, tissue)))
acc_cancer_Tcells_caf = AddMetaData(object = acc_cancer_Tcells_caf,metadata = metadata[,"cell_type",drop=F],col.name = "cell_type")

```

```{r}
saveRDS(acc_cancer_Tcells_caf,file = paste0(params$data_out_dir, basename(output$acc_cancer_Tcells_caf)))
```