---
title: 'create_data_for_CIBERSORT' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
---
```{r}
library(stringi)
library(Seurat)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(data.table)
library(print.rmd.tabs)
```


```{r}
source("./pipe.R")
input = pipeline$create_ferrarotto_matrix$input
output = pipeline$create_ferrarotto_matrix$output
```


# create Bulk RNA-seq data to be deconv
```{r}
ferra_acc = readxl::read_excel(input$ferra_acc,sheet = 1,col_names = T,skip = 0) %>% as.data.frame()
```

```{r}
rownames(ferra_acc) = make.unique(ferra_acc$gene_name)
ferra_acc$gene_name = NULL
```

```{r}
# convert to TPM
ferrarotto_tpm <- apply(ferra_acc, 2, function(x) (x / sum(x)) * 10^6)
```


```{r}
colnames(ferra_acc)  = colnames(ferra_acc) %>% gsub(replacement = "_",pattern = "-") # cibersort don't accept "-"
```

```{r}
dim(ferra_acc)
```

```{r}
fwrite(ferra_acc,file = params$data_out_dir %s+% basename(output$ferra_exprs), sep = "\t",row.names = T)
```



