---
title: 'create_data_for_CIBERSORT' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
---
```{r}
library(stringi)
library(Seurat)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(data.table)
library(print.rmd.tabs)
```


```{r}
source("./pipe.R")
input = pipeline$create_dou_matrix$input
output = pipeline$create_dou_matrix$output
```


# create Bulk RNA-seq data to be deconv
```{r}
dou_exprs = readxl::read_excel(input$dou_acc,sheet = 2,col_names = T,skip = 1) %>% as.data.frame()
dou_clinical = readxl::read_excel(input$dou_clinical,sheet = 1,col_names = T,skip = 1) %>% as.data.frame()

```

```{r}
library(biomaRt)
#convert from ensmle to gene symbols 

ensembl <- useEnsembl(biomart = "genes", dataset = "hsapiens_gene_ensembl")

ensembl_ids <- dou_exprs$GeneID


mapped_genes <- getBM(
  attributes = c("ensembl_gene_id", "hgnc_symbol"),
  filters = "ensembl_gene_id",
  values = ensembl_ids,
  mart = ensembl
)
# Return the gene symbols (hgnc_symbol) in the original order of the Ensembl IDs, including NA for unmatched entries
mapped_ordered <- mapped_genes$hgnc_symbol[match(ensembl_ids, mapped_genes$ensembl_gene_id)]


dou_exprs$gene_symbol = mapped_ordered
dou_exprs= dou_exprs %>% na.omit()
rownames(dou_exprs) = dou_exprs$gene_symbol %>% make.unique()
dou_exprs$GeneID <- NULL
dou_exprs$gene_symbol <- NULL
```


```{r}
# filter only primary samples
primary_samples = dou_clinical %>% filter(`Types of surgical sample` == "Primary") %>% pull("Case Number" )
dou_exprs = dou_exprs[,colnames(dou_exprs) %in% primary_samples]

dou_exprs$`P-50`<- NULL # almost all 0 expression
colnames(dou_exprs)  = colnames(dou_exprs) %>% gsub(replacement = "_",pattern = "-") # cibersort don't accept "-"
```

```{r}
dim(dou_exprs)
```

```{r}
fwrite(dou_exprs,file = params$data_out_dir %s+% basename(output$dou_exprs), sep = "\t",row.names = T)
```



