---
title: 'Dou_CIBERSORT_analysis' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
---
```{r}
library(stringi)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(data.table)
library(print.rmd.tabs)
library(grid)
library(ComplexHeatmap)
```

```{r}
source("./pipe.R")
input = pipeline$Dou_CIBERSORT_analysis$input
output = pipeline$Dou_CIBERSORT_analysis$output
```


```{r}
dou_survival = readxl::read_excel(input$dou_acc_survival,sheet = 1,col_names = T,skip = 1) %>% as.data.frame()
```

```{r}
print(input$cs_result)
```

```{r}
deconv_result = fread(input$cs_result)
deconv_result
```

```{r}
dou_survival= dou_survival[dou_survival$"Case Number" != "P-50",]

# make case number in dou_survival the same format as in deconv_result
dou_survival$`Case Number` = gsub(pattern = "-", replacement = "_", dou_survival$`Case Number`)

dou_survival = dou_survival %>% filter(`Case Number` %in% deconv_result$Mixture) 
```

# Histopathology- lum/myo ratio 
```{r}

df = data.frame(lum_ratio = deconv_result$Luminal/(deconv_result$Luminal + deconv_result$Myo) ,
                  Histopathology = dou_survival$Histopathology)

# Convert all text to lowercase (or use str_to_title() for capitalized)
df$Histopathology <- tolower(df$Histopathology)

# Remove leading and trailing whitespace
df$Histopathology <- trimws(df$Histopathology)

# Replace multiple spaces (or other whitespace) with a single space
df$Histopathology <- gsub("[[:space:]]+", " ", df$Histopathology)
df$Histopathology <- gsub("mixed， solid component<30%", "mixed, solid component<30%", df$Histopathology)


```

```{r}
library(dplyr)
library(ggplot2)

# Step 1: summary per category
df_summary <- df %>%
  group_by(Histopathology) %>%
  dplyr::summarise(
    mean_ratio = mean(lum_ratio[is.finite(lum_ratio)]),
    .groups = "drop"
  )

# Step 2: barplot with discrete fill
ggplot(df_summary, aes(x = reorder(Histopathology, -mean_ratio), y = mean_ratio)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_fill_brewer(palette = "Blues", direction = 1) +  # discrete color scale
  labs(
    x = "Histopathology",
    y = "Mean lum_ratio",
  ) +
  theme_minimal()

```

# Treshold

```{r}
ratio_threshold = 0.5
df <- df %>%
  mutate(
    LumCategory = ifelse(lum_ratio > ratio_threshold, paste("High (>",ratio_threshold,")"), paste("Low (<=",ratio_threshold,")"))
  )

my_colors <- c(
  "solid" = "red",
  "mixed cribriform-solid type" = "pink",
  "mixed, solid component<30%" = "coral1",
  "mixed" = "orange",
  "cribriform" = "blue",
  "tubular" = "deepskyblue",
  "mix of tubular and cribriform" = "cyan",
  "unknown" = "grey",
  "adenoid cystic carcinoma ex pleomorphic adenomas" = "black"
)

df$Histopathology <- factor(df$Histopathology, levels = c(
names(my_colors)
))


ggplot(df, aes(x = LumCategory, fill = Histopathology)) +
  geom_bar(position = "fill") +  
  labs(
    title = "Distribution of Histopathology by Luminal Ratio Category",
    x = "Luminal Ratio Category",
    y = "Proportion"
  ) +
  scale_fill_manual(values = my_colors) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


# fraction-clinical correlations
```{r}


# make case number in dou_survival the same format as in deconv_result
dou_survival$`Case Number` = gsub(pattern = "-", replacement = "_", dou_survival$`Case Number`)

deconv_result_with_survival = deconv_result %>% as.data.frame()

clinical_cols = c("Immune infiltration score (IIS)", "T cell infiltration score (TIS)","Antigen presenting machinery (APM)","indel_TMB","Tumour mutational burden (TMB)","Locoregional recurrence-free survival (LRRFS)","Distant metastasis-free survival time (DMFS)")
# join clinical data to deconv result
deconv_result_with_survival  =  inner_join(deconv_result_with_survival, dou_survival %>% select(clinical_cols,"Case Number")
                                           ,by = c("Mixture" = "Case Number"))
# remove columns that are not cell types or clinical data
deconv_result_with_survival = deconv_result_with_survival %>% 
  select(-c("Mixture", "P-value", "Correlation","RMSE"))

```


# cells ratio
```{r}


# calculate  T cells ratio
t_cells_names = c( "CD8_Naive", "CD4_Naive", "CD8_CM", "CD4_CM", "CD4_EM", "CD8_EM", "gdT",
                   "Treg", "CD8_TEMRA","MAIT")

cell_types_cols = c("t_cells_ratio", "immune_cells_ratio", "lum_ratio")
deconv_ratio_with_survival = deconv_result_with_survival
deconv_ratio_with_survival$t_cells_ratio = rowSums(deconv_ratio_with_survival[, colnames(deconv_ratio_with_survival) %in% t_cells_names])


# Calculate Immune cells ratio
immune_cells_names = c( "Naive B", "CD8_Naive", "CD4_Naive", 
"CD8_CM", "CD4_CM", "CD4_EM", "CD8_EM", "Plasmacytoid Dendritic", 
"gdT", "Treg", "CD8_TEMRA", "Macrophages", "Basophils", "Neutrophils", 
"MAIT", "Plasma B", "Myeloid Dendritic")
immune_cells_names = immune_cells_names[immune_cells_names %in% colnames(deconv_ratio_with_survival)]

for (cell_name in immune_cells_names) {
  cell_ratio = deconv_ratio_with_survival[,cell_name]/rowSums(deconv_ratio_with_survival[,immune_cells_names])
  deconv_ratio_with_survival[,paste0(cell_name,"_ratio")] = cell_ratio
  cell_types_cols = c(cell_types_cols, paste0(cell_name,"_ratio"))
}



deconv_ratio_with_survival$immune_cells_ratio = rowSums(deconv_ratio_with_survival[, colnames(deconv_ratio_with_survival) %in% immune_cells_names])

deconv_ratio_with_survival$lum_ratio = deconv_ratio_with_survival$Luminal/(deconv_ratio_with_survival$Luminal + deconv_ratio_with_survival$Myo)

# remove original immune cells columns
for (cell_name in immune_cells_names) {
    deconv_ratio_with_survival[,cell_name] <- NULL
}

deconv_ratio_with_survival$Myo <- NULL
deconv_ratio_with_survival$Luminal <- NULL
```

```{r}
zero_cols = colnames(deconv_ratio_with_survival)[colSums(deconv_ratio_with_survival )==0]
cell_types_cols = cell_types_cols[!cell_types_cols %in% zero_cols]
```

```{r}
# calculate correlation between cell types and clinical data
correlation_matrix <- cor(
  x = deconv_ratio_with_survival[,cell_types_cols],
  y = deconv_ratio_with_survival[,clinical_cols],
  method = "pearson" 
)
all_pairs = expand.grid(
  Item_A = rownames(correlation_matrix), 
  Item_B = colnames(correlation_matrix)
)


p_values_vector = apply(all_pairs, MARGIN = 1, FUN = function(x){
  pair_a = x[[1]]
  pair_b = x[[2]]
  p_val = cor.test(deconv_ratio_with_survival[[pair_a]], deconv_ratio_with_survival[[pair_b]])[["p.value"]]
    }
) %>% p.adjust(method = "fdr")

all_pvals = matrix(
  p_values_vector,
  nrow = nrow(correlation_matrix),
  ncol = ncol(correlation_matrix)
) %>% as.data.frame()
rownames(all_pvals) = rownames(correlation_matrix)
colnames(all_pvals) = colnames(correlation_matrix)

```


```{r}
convert <- function(vec) {
  symnum(vec, corr = FALSE, na = FALSE, cutpoints = c(0, 
    0.001, 0.01, 0.05, 0.1, 1), symbols = c("***", "**", "*", ".", " ")) %>% as.character()
} 
all_pvals[] = apply(all_pvals, MARGIN = 2, FUN = convert)
```

```{r fig.height=8, fig.width=15}


col_fun = circlize::colorRamp2(c(-1, 0, 1), c("royalblue4", "white", "red"))
p = ComplexHeatmap::Heatmap(t(correlation_matrix),  row_names_gp = gpar(fontsize = 14), column_names_gp = gpar(fontsize = 14), 
                            name = "Pearson",
                            clustering_method_rows = "average",show_heatmap_legend = T,col = col_fun, 
                            clustering_distance_rows = "euclidean", 
                            cell_fun = function(j, i, x, y, width, height, fill) {
                              grid.text(t(all_pvals)[i, j], x, y, gp = gpar(fontsize = 14))
                              },
                            column_names_rot =45,column_title = "cell types %",column_title_side = "bottom",
                            row_title = "patient data", row_title_side = "right"
    
)

p
```



```{r}
cell_type = "lum_ratio"
data = data.frame(fraction = deconv_ratio_with_survival[[cell_type]],
                  TIS = deconv_ratio_with_survival$`T cell infiltration score (TIS)`)

library(ggplot2)
library(ggpubr) 

ggscatter(data, x = "fraction", y = "TIS", add = "reg.line") +
  stat_cor() + theme_minimal()+  geom_smooth(method = "lm", se = FALSE, color = "blue") +xlab(cell_type)


```

# cell types- survival
```{r}
x = "Distant metastasis-free survival time (DMFS)"
y = "Locoregional recurrence-free survival (LRRFS)"
data = data.frame(fraction = dou_survival[[x]],
                  survival = dou_survival[[y]])

library(ggplot2)
library(ggpubr) 
# יצירת גרף הפיזור הבסיסי
p <- ggplot(data, aes(x = fraction, y = survival)) +
  geom_point() + # הוספת נקודות הפיזור
  labs(title = "Survival vs. Fraction",
       x = x,
       y = y) +
  theme_minimal()+ # רקע נקי יותר +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`, `~")),
           label.x = 0.4, label.y = 130) 
p
```

```{r}
cell_type = "Luminal"
data = data.frame(fraction = deconv_result[[cell_type]],
                  survival = dou_survival$`Locoregional recurrence-free survival (LRRFS)`)

library(ggplot2)
library(ggpubr) 
# יצירת גרף הפיזור הבסיסי
p <- ggplot(data, aes(x = fraction, y = survival)) +
  geom_point() + # הוספת נקודות הפיזור
  labs(title = "Survival vs. Fraction",
       x = paste (cell_type, "Fraction"),
       y = "recurrence-free survival") +
  theme_minimal()+ # רקע נקי יותר +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`, `~")),
           label.x = 0.4, label.y = 130) 
p
```
```{r}
cell_type = "CD8_TEMRA"
data = data.frame(fraction = deconv_result[[cell_type]],
                  survival =dou_survival$`Locoregional recurrence-free survival (LRRFS)`)

library(ggplot2)
library(ggpubr) 
# יצירת גרף הפיזור הבסיסי
p <- ggplot(data, aes(x = fraction, y = survival)) +
  geom_point() + # הוספת נקודות הפיזור
  labs(title = "Survival vs. Fraction",
       x = paste (cell_type, "Fraction"),
       y = "recurrence-free survival") +
  theme_minimal()+ # רקע נקי יותר +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`, `~")),
           label.x = 0.05, label.y = 130) + ggtitle(cell_type) 
p
```

```{r}
cell_type = "CAF"
data = data.frame(fraction = deconv_result[[cell_type]],
                  survival =dou_survival$`Locoregional recurrence-free survival (LRRFS)`)

library(ggplot2)
library(ggpubr) 
# יצירת גרף הפיזור הבסיסי
p <- ggplot(data, aes(x = fraction, y = survival)) +
  geom_point() + # הוספת נקודות הפיזור
  labs(title = "Survival vs. Fraction",
       x = paste (cell_type, "Fraction"),
       y = "recurrence-free survival") +
  theme_minimal()+ # רקע נקי יותר +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`, `~")),
           label.x = 0.02, label.y = 130) + ggtitle(cell_type) 
p
```
```{r}
deconv_with_survival_aggTcells = deconv_result_with_survival
```

```{r}
#only T cells, collapse T cells subtypes
naive_t_cells = c("CD8_Naive", "CD4_Naive")
CD8_memory = c("CD8_CM", "CD8_EM","CD8_TEMRA")
CD4_helper = c("CD4_CM", "CD4_EM")
T_Innate_like = c("gdT", "MAIT")

all_t_subtypes = list("naive_t_cells" = naive_t_cells, "CD8_memory" = CD8_memory, "CD4_helper" = CD4_helper, "T_Innate_like" = T_Innate_like)
```

```{r}
# Calculate Immune cells ratio
immune_cells_names = c( "Naive B", "CD8_Naive", "CD4_Naive", 
"CD8_CM", "CD4_CM", "CD4_EM", "CD8_EM", "Plasmacytoid Dendritic", 
"gdT", "Treg", "CD8_TEMRA", "Macrophages", "Basophils", "Neutrophils", 
"MAIT", "Plasma B", "Myeloid Dendritic")
immune_cells_names = immune_cells_names[immune_cells_names %in% colnames(deconv_with_survival_aggTcells)]

deconv_with_survival_aggTcells$immune_cells_ratio = rowSums(deconv_with_survival_aggTcells[, colnames(deconv_with_survival_aggTcells) %in% immune_cells_names])
```


```{r}
deconv_with_survival_aggTcells = deconv_with_survival_aggTcells %>% select(c(t_cells_names,clinical_cols,"Luminal","Myo","immune_cells_ratio"))

for (t_subtype_name in names(all_t_subtypes)) {
  subtypes = all_t_subtypes[[t_subtype_name]]
  # calculate the sum of the subtypes for each row and add it as a new column
  deconv_with_survival_aggTcells = deconv_with_survival_aggTcells %>% 
    mutate(!!t_subtype_name := rowSums(deconv_with_survival_aggTcells[, colnames(deconv_with_survival_aggTcells) %in% subtypes]))
  # calculate the ratio of the subtypes to the total immune cells and add it as a new column
  deconv_with_survival_aggTcells[[paste0(t_subtype_name, "_ratio")]] = deconv_with_survival_aggTcells[[t_subtype_name]] /
    deconv_with_survival_aggTcells$immune_cells_ratio
  # remove the original subtypes columns
  deconv_with_survival_aggTcells = deconv_with_survival_aggTcells %>% select(-all_of(subtypes))
} 
deconv_with_survival_aggTcells$Treg_ratio = deconv_with_survival_aggTcells$Treg / deconv_with_survival_aggTcells$immune_cells_ratio

deconv_with_survival_aggTcells$lum_ratio = deconv_with_survival_aggTcells$Luminal/(deconv_with_survival_aggTcells$Luminal + deconv_with_survival_aggTcells$Myo)


deconv_with_survival_aggTcells$Myo <- NULL
deconv_with_survival_aggTcells$Luminal <- NULL

```

```{r}
cell_types_cols = c(names(all_t_subtypes) , "lum_ratio", "Treg")
```

```{r}
zero_cols = colnames(deconv_with_survival_aggTcells)[colSums(deconv_with_survival_aggTcells )==0]
cell_types_cols = cell_types_cols[!cell_types_cols %in% zero_cols]
```

```{r}
# calculate correlation between cell types and clinical data
correlation_matrix <- cor(
  x = deconv_with_survival_aggTcells[,cell_types_cols],
  y = deconv_with_survival_aggTcells[,clinical_cols],
  method = "pearson" 
)
all_pairs = expand.grid(
  Item_A = rownames(correlation_matrix), 
  Item_B = colnames(correlation_matrix)
)


p_values_vector = apply(all_pairs, MARGIN = 1, FUN = function(x){
  pair_a = x[[1]]
  pair_b = x[[2]]
  p_val = cor.test(deconv_with_survival_aggTcells[[pair_a]], deconv_with_survival_aggTcells[[pair_b]])[["p.value"]]
    }
) %>% p.adjust(method = "fdr")

all_pvals = matrix(
  p_values_vector,
  nrow = nrow(correlation_matrix),
  ncol = ncol(correlation_matrix)
) %>% as.data.frame()
rownames(all_pvals) = rownames(correlation_matrix)
colnames(all_pvals) = colnames(correlation_matrix)

```


```{r}
convert <- function(vec) {
  symnum(vec, corr = FALSE, na = FALSE, cutpoints = c(0, 
    0.001, 0.01, 0.05, 0.1, 1), symbols = c("***", "**", "*", ".", " ")) %>% as.character()
} 
all_pvals[] = apply(all_pvals, MARGIN = 2, FUN = convert)
```

```{r fig.height=8, fig.width=15}


col_fun = circlize::colorRamp2(c(-1, 0, 1), c("royalblue4", "white", "red"))
p = ComplexHeatmap::Heatmap(t(correlation_matrix),  row_names_gp = gpar(fontsize = 14), column_names_gp = gpar(fontsize = 14), 
                            name = "Pearson",
                            clustering_method_rows = "average",show_heatmap_legend = T,col = col_fun, 
                            clustering_distance_rows = "euclidean", 
                            cell_fun = function(j, i, x, y, width, height, fill) {
                              grid.text(t(all_pvals)[i, j], x, y, gp = gpar(fontsize = 14))
                              },
                            column_names_rot =45,column_title = "cell types %",column_title_side = "bottom",
                            row_title = "patient data", row_title_side = "right"
    
)

p
```
# T subtypes agg ration correlations



```{r}
cell_types_cols = c(paste0(names(all_t_subtypes),"_ratio") , "lum_ratio", "Treg_ratio")
```

```{r}
zero_cols = colnames(deconv_with_survival_aggTcells)[colSums(deconv_with_survival_aggTcells )==0]
cell_types_cols = cell_types_cols[!cell_types_cols %in% zero_cols]
```

```{r}
# calculate correlation between cell types and clinical data
correlation_matrix <- cor(
  x = deconv_with_survival_aggTcells[,cell_types_cols],
  y = deconv_with_survival_aggTcells[,clinical_cols],
  method = "pearson" 
)
all_pairs = expand.grid(
  Item_A = rownames(correlation_matrix), 
  Item_B = colnames(correlation_matrix)
)


p_values_vector = apply(all_pairs, MARGIN = 1, FUN = function(x){
  pair_a = x[[1]]
  pair_b = x[[2]]
  p_val = cor.test(deconv_with_survival_aggTcells[[pair_a]], deconv_with_survival_aggTcells[[pair_b]])[["p.value"]]
    }
) %>% p.adjust(method = "fdr")

all_pvals = matrix(
  p_values_vector,
  nrow = nrow(correlation_matrix),
  ncol = ncol(correlation_matrix)
) %>% as.data.frame()
rownames(all_pvals) = rownames(correlation_matrix)
colnames(all_pvals) = colnames(correlation_matrix)

```


```{r}
convert <- function(vec) {
  symnum(vec, corr = FALSE, na = FALSE, cutpoints = c(0, 
    0.001, 0.01, 0.05, 0.1, 1), symbols = c("***", "**", "*", ".", " ")) %>% as.character()
} 
all_pvals[] = apply(all_pvals, MARGIN = 2, FUN = convert)
```

```{r fig.height=8, fig.width=13}


col_fun = circlize::colorRamp2(c(-1, 0, 1), c("royalblue4", "white", "red"))
p = ComplexHeatmap::Heatmap(t(correlation_matrix),  row_names_gp = gpar(fontsize = 10), column_names_gp = gpar(fontsize = 14), 
                            name = "Pearson",
                            clustering_method_rows = "average",show_heatmap_legend = T,col = col_fun, 
                            clustering_distance_rows = "euclidean", 
                            cell_fun = function(j, i, x, y, width, height, fill) {
                              grid.text(t(all_pvals)[i, j], x, y, gp = gpar(fontsize = 14))
                              },
                            column_names_rot =45,column_title = "cell types %",column_title_side = "bottom",
                            row_title = "patient data", row_title_side = "right"
    
)

p
```

# only cell types correlations

```{r}
cell_types_cols = c(names(all_t_subtypes) , "lum_ratio", "Treg")
```



```{r}
# calculate correlation between cell types and clinical data
correlation_matrix <- cor(
  x = deconv_with_survival_aggTcells[,cell_types_cols],
  y = deconv_with_survival_aggTcells[,cell_types_cols],
  method = "pearson" 
)
all_pairs = expand.grid(
  Item_A = rownames(correlation_matrix), 
  Item_B = colnames(correlation_matrix)
)


p_values_vector = apply(all_pairs, MARGIN = 1, FUN = function(x){
  pair_a = x[[1]]
  pair_b = x[[2]]
  p_val = cor.test(deconv_with_survival_aggTcells[[pair_a]], deconv_with_survival_aggTcells[[pair_b]])[["p.value"]]
    }
) %>% p.adjust(method = "fdr")

all_pvals = matrix(
  p_values_vector,
  nrow = nrow(correlation_matrix),
  ncol = ncol(correlation_matrix)
) %>% as.data.frame()
rownames(all_pvals) = rownames(correlation_matrix)
colnames(all_pvals) = colnames(correlation_matrix)

```


```{r}
convert <- function(vec) {
  symnum(vec, corr = FALSE, na = FALSE, cutpoints = c(0, 
    0.001, 0.01, 0.05, 0.1, 1), symbols = c("***", "**", "*", ".", " ")) %>% as.character()
} 
all_pvals[] = apply(all_pvals, MARGIN = 2, FUN = convert)
```

```{r fig.height=8, fig.width=15}


col_fun = circlize::colorRamp2(c(-1, 0, 1), c("royalblue4", "white", "red"))
p = ComplexHeatmap::Heatmap(t(correlation_matrix),  row_names_gp = gpar(fontsize = 14), column_names_gp = gpar(fontsize = 14), 
                            name = "Pearson",
                            clustering_method_rows = "average",show_heatmap_legend = T,col = col_fun, 
                            clustering_distance_rows = "euclidean", 
                            cell_fun = function(j, i, x, y, width, height, fill) {
                              grid.text(t(all_pvals)[i, j], x, y, gp = gpar(fontsize = 14))
                              },
                            column_names_rot =45,column_title = "cell types %",column_title_side = "bottom",
                            row_title = "cell types %", row_title_side = "right"
    
)

p
```

```{r}

cell_types_cols = c(paste0(names(all_t_subtypes),"_ratio") , "lum_ratio", "Treg_ratio")
```



```{r}
# calculate correlation between cell types and clinical data
correlation_matrix <- cor(
  x = deconv_with_survival_aggTcells[,cell_types_cols],
  y = deconv_with_survival_aggTcells[,cell_types_cols],
  method = "pearson" 
)
all_pairs = expand.grid(
  Item_A = rownames(correlation_matrix), 
  Item_B = colnames(correlation_matrix)
)


p_values_vector = apply(all_pairs, MARGIN = 1, FUN = function(x){
  pair_a = x[[1]]
  pair_b = x[[2]]
  p_val = cor.test(deconv_with_survival_aggTcells[[pair_a]], deconv_with_survival_aggTcells[[pair_b]])[["p.value"]]
    }
) %>% p.adjust(method = "fdr")

all_pvals = matrix(
  p_values_vector,
  nrow = nrow(correlation_matrix),
  ncol = ncol(correlation_matrix)
) %>% as.data.frame()
rownames(all_pvals) = rownames(correlation_matrix)
colnames(all_pvals) = colnames(correlation_matrix)

```


```{r}
convert <- function(vec) {
  symnum(vec, corr = FALSE, na = FALSE, cutpoints = c(0, 
    0.001, 0.01, 0.05, 0.1, 1), symbols = c("***", "**", "*", ".", " ")) %>% as.character()
} 
all_pvals[] = apply(all_pvals, MARGIN = 2, FUN = convert)
```

```{r fig.height=8, fig.width=15}


col_fun = circlize::colorRamp2(c(-1, 0, 1), c("royalblue4", "white", "red"))
p = ComplexHeatmap::Heatmap(t(correlation_matrix),  row_names_gp = gpar(fontsize = 14), column_names_gp = gpar(fontsize = 14),
                            name = "Pearson",
                            clustering_method_rows = "average",show_heatmap_legend = T,col = col_fun, 
                            clustering_distance_rows = "euclidean", 
                            cell_fun = function(j, i, x, y, width, height, fill) {
                              grid.text(t(all_pvals)[i, j], x, y, gp = gpar(fontsize = 14))
                              },
                            column_names_rot =45,column_title = "cell types %",column_title_side = "bottom",
                            row_title = "cell types %", row_title_side = "right"
    
)

p
```
```{r}
x = "lum_ratio"
y = "Distant metastasis-free survival time (DMFS)" #"Distant metastasis-free survival time (DMFS), #"Locoregional recurrence-free survival (LRRFS)"
data = data.frame(fraction = deconv_with_survival_aggTcells[[x]],
                  survival = deconv_with_survival_aggTcells[[y]])

library(ggplot2)
library(ggpubr) 
# יצירת גרף הפיזור הבסיסי
p <- ggplot(data, aes(x = fraction, y = survival)) +
  geom_point() + # הוספת נקודות הפיזור
  labs(title = "Survival vs. Fraction",
       x = x,
       y = y) +
  theme_minimal()+ # רקע נקי יותר +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`, `~")),
           label.x = 0.4, label.y = 130) 
p
```
