---
title: "Ferrarotto_CIBERSORT_analsyis"
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
---
```{r}
library(stringi)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(data.table)
library(print.rmd.tabs)
library(grid)
library(ComplexHeatmap)
```

```{r}
source("./pipe.R")
input = pipeline$ferrarotto_CIBERSORT_analysis$input
output = pipeline$ferrarotto_CIBERSORT_analysis$output
```


```{r}
ferra_clinical = readxl::read_excel(input$ferra_clinical,sheet = 1,col_names = T,skip = 0) %>% as.data.frame()
```


```{r}
deconv_result = fread(input$cs_result)
deconv_result
```

```{r}

# make case number in ferra_clinical the same format as in deconv_result
ferra_clinical$TID = gsub(pattern = "-", replacement = "_", ferra_clinical$TID)

ferra_clinical = ferra_clinical %>% filter(TID %in% deconv_result$Mixture) 
```

# Histopathology- lum/myo ratio 
```{r}
ferra_clinical$Subtype = ferra_clinical$Subtype %>%  gsub(pattern = "S",replacement = "solid") %>% gsub(pattern = "9",replacement = "unknown") %>% gsub(pattern = "C",replacement = "cribriform") %>% gsub(pattern = "T",replacement = "tubular")

df = data.frame(lum_ratio = deconv_result$Luminal/(deconv_result$Luminal + deconv_result$Myo) ,
                  Histopathology = ferra_clinical$Subtype)


```

```{r}
library(dplyr)
library(ggplot2)

# Step 1: summary per category
df_summary <- df %>%
  group_by(Histopathology) %>%
  dplyr::summarise(
    mean_ratio = mean(lum_ratio[is.finite(lum_ratio)]),
    .groups = "drop"
  )

# Step 2: barplot with discrete fill
ggplot(df_summary, aes(x = reorder(Histopathology, -mean_ratio), y = mean_ratio)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_fill_brewer(palette = "Blues", direction = 1) +  # discrete color scale
  labs(
    x = "Histopathology",
    y = "Mean lum_ratio",
  ) +
  theme_minimal()

```

# Treshold

```{r}
ratio_threshold = 0.7
df <- df %>%
  mutate(
    LumCategory = ifelse(lum_ratio > ratio_threshold, paste("High (>",ratio_threshold,")"), paste("Low (<=",ratio_threshold,")"))
  )

my_colors <- c(
  "solid" = "red",
  "mixed cribriform-solid type" = "pink",
  "mixed, solid component<30%" = "coral1",
  "mixed" = "orange",
  "cribriform" = "blue",
  "tubular" = "deepskyblue",
  "mix of tubular and cribriform" = "cyan",
  "unknown" = "grey",
  "adenoid cystic carcinoma ex pleomorphic adenomas" = "black"
)

df$Histopathology <- factor(df$Histopathology, levels = c(
names(my_colors)
))


ggplot(df, aes(x = LumCategory, fill = Histopathology)) +
  geom_bar(position = "fill") +  
  labs(
    title = "Distribution of Histopathology by Luminal Ratio Category",
    x = "Luminal Ratio Category",
    y = "Proportion"
  ) +
  scale_fill_manual(values = my_colors) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

# survival
```{r}

# require("survival")
# library("survminer")
# ferra_clinical = inner_join(ferra_clinical, deconv_result, by = c("TID" = "Mixture"))
# ferra_clinical$lum_ratio = ferra_clinical$Luminal/(ferra_clinical$Luminal + ferra_clinical$Myo)

```


# 
```{r}

deconv_result_with_survival = deconv_result %>% as.data.frame()

# join clinical data to deconv result
deconv_result_with_survival  =  inner_join(deconv_result_with_survival, ferra_clinical
                                           ,by = c("Mixture" = "TID"))

# remove columns that are not cell types or clinical data
deconv_result_with_survival = deconv_result_with_survival %>% 
  select(-c("Mixture", "P-value", "Correlation","RMSE"))
```



```{r}
#only T cells, collapse T cells subtypes
naive_t_cells = c("CD8_Naive", "CD4_Naive")
CD8_memory = c("CD8_CM", "CD8_EM","CD8_TEMRA")
CD4_helper = c("CD4_CM", "CD4_EM")
T_Innate_like = c("gdT", "MAIT")

all_t_subtypes = list("naive_t_cells" = naive_t_cells, "CD8_memory" = CD8_memory, "CD4_helper" = CD4_helper, "T_Innate_like" = T_Innate_like)
```

```{r}
# Calculate Immune cells ratio
immune_cells_names = c( "Naive B", "CD8_Naive", "CD4_Naive", 
"CD8_CM", "CD4_CM", "CD4_EM", "CD8_EM", "Plasmacytoid Dendritic", 
"gdT", "Treg", "CD8_TEMRA", "Macrophages", "Basophils", "Neutrophils", 
"MAIT", "Plasma B", "Myeloid Dendritic")
immune_cells_names = immune_cells_names[immune_cells_names %in% colnames(deconv_result_with_survival)]

deconv_result_with_survival$immune_cells_fraction = rowSums(deconv_result_with_survival[, colnames(deconv_result_with_survival) %in% immune_cells_names])
```


```{r}
#deconv_result_with_survival = deconv_result_with_survival %>% select(c(t_cells_names,clinical_cols,"Luminal","Myo","immune_cells_fraction"))

for (t_subtype_name in names(all_t_subtypes)) {
  subtypes = all_t_subtypes[[t_subtype_name]]
  # calculate the sum of the subtypes for each row and add it as a new column
  deconv_result_with_survival = deconv_result_with_survival %>% 
    mutate(!!t_subtype_name := rowSums(deconv_result_with_survival[, colnames(deconv_result_with_survival) %in% subtypes]))
  # calculate the ratio of the subtypes to the total immune cells and add it as a new column
  deconv_result_with_survival[[paste0(t_subtype_name, "/immune_cells")]] = deconv_result_with_survival[[t_subtype_name]] /
    deconv_result_with_survival$immune_cells_fraction
  # remove the original subtypes columns
  deconv_result_with_survival = deconv_result_with_survival %>% select(-all_of(subtypes))
} 
deconv_result_with_survival[,"Treg/immune_cells"] = deconv_result_with_survival$Treg / deconv_result_with_survival$immune_cells_fraction

deconv_result_with_survival$lum_ratio = deconv_result_with_survival$Luminal/(deconv_result_with_survival$Luminal + deconv_result_with_survival$Myo)


deconv_result_with_survival$Myo <- NULL
deconv_result_with_survival$Luminal <- NULL

```


```{r}
#scatter plot "M" vs "lum_ratio"
deconv_result_with_survival$T = as.character(deconv_result_with_survival$T)
deconv_result_with_survival$M = as.character(deconv_result_with_survival$M)
deconv_result_with_survival$N = as.character(deconv_result_with_survival$N)

ggplot(deconv_result_with_survival, aes(x = N, y = lum_ratio)) +
  geom_boxplot()+
  geom_jitter()+
  theme_minimal()
```

```{r}
cell_types_cols = c(paste0(names(all_t_subtypes),"/immune_cells") , "lum_ratio", "Treg/immune_cells")
```





```{r}
# calculate correlation between cell types and clinical data
correlation_matrix <- cor(
  x = deconv_result_with_survival[,cell_types_cols],
  y = deconv_result_with_survival[,cell_types_cols],
  method = "pearson" 
)
all_pairs = expand.grid(
  Item_A = rownames(correlation_matrix), 
  Item_B = colnames(correlation_matrix)
)


p_values_vector = apply(all_pairs, MARGIN = 1, FUN = function(x){
  pair_a = x[[1]]
  pair_b = x[[2]]
  p_val = cor.test(deconv_result_with_survival[[pair_a]], deconv_result_with_survival[[pair_b]])[["p.value"]]
    }
) %>% p.adjust(method = "fdr")

all_pvals = matrix(
  p_values_vector,
  nrow = nrow(correlation_matrix),
  ncol = ncol(correlation_matrix)
) %>% as.data.frame()
rownames(all_pvals) = rownames(correlation_matrix)
colnames(all_pvals) = colnames(correlation_matrix)

```


```{r}
convert <- function(vec) {
  symnum(vec, corr = FALSE, na = FALSE, cutpoints = c(0, 
    0.001, 0.01, 0.05, 0.1, 1), symbols = c("***", "**", "*", ".", " ")) %>% as.character()
} 
all_pvals[] = apply(all_pvals, MARGIN = 2, FUN = convert)
```

```{r fig.height=8, fig.width=15}


col_fun = circlize::colorRamp2(c(-1, 0, 1), c("royalblue4", "white", "red"))
p = ComplexHeatmap::Heatmap(t(correlation_matrix),  row_names_gp = gpar(fontsize = 14),  column_names_gp = gpar(fontsize = 14), 
                            name = "Pearson",
                            clustering_method_rows = "average",show_heatmap_legend = T,col = col_fun,   clustering_method_columns = "average",
                            clustering_distance_rows = "euclidean", 
                            cell_fun = function(j, i, x, y, width, height, fill) {
                              grid.text(t(all_pvals)[i, j], x, y, gp = gpar(fontsize = 14))
                              },
                            column_names_rot =45,column_title = "cell types %",column_title_side = "bottom",
                            row_title = "cell types %", row_title_side = "right"
    
)

p
```