---
title: 'LIANA' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
  debug: FALSE
---

```{r}
library(tidyverse)
library(liana)
library(nichenetr)
library(Seurat)
library(ggrepel)
library(cowplot)
library(readxl)
```

```{r setup}
if(Sys.getenv("POSITRON") == "1"){
    setwd(here::here())
    params <- rmarkdown::yaml_front_matter(rstudioapi::getSourceEditorContext()$path)$params
}
```





```{r}
source("./pipe.R")
input = pipeline$liana$input
output = pipeline$liana$output
```

```{r}
liana_results = readRDS(file = input$liana_result)
```



# Plot T cells to cancer cells interactions

```{r fig.height=8, fig.width=15}
#| fig-height: 8
#| fig-width: 15
if (params$debug) {
  print("Running in debug mode, using only 3 cell types and 50 genes for LIANA")
  source_groups = c("CD8_CM")
  target_groups = c("Luminal","Myo")
}else{
  source_groups = c( "CD8_CM", 
"gdT", "CD8_Naive", "CD4_EM", 
"CD4_CM", "CD4_Naive", "CD8_TEMRA", "MAIT", "CD8_EM","Treg") 
  target_groups = c("Luminal","Myo")
}
threshold = 0.001
liana_mod <- liana_results %>%
    # Filter to only the cells of interest
    `if`(!is.null(source_groups),
         filter(., source %in% source_groups),
         .) %>%
    `if`(!is.null(target_groups),
         filter(., target %in% target_groups),
         .)

top_interactions = liana_results %>%
  filter(aggregate_rank <= threshold) %>% 
  distinct_at(c("ligand.complex", "receptor.complex"))

liana_mod %<>% inner_join(top_interactions, by=c("ligand.complex", "receptor.complex"))

cd8_cells = c("CD8_CM", "CD8_Naive", "CD8_TEMRA", "CD8_EM")
cd4_cells = c("CD4_EM", "CD4_CM", "CD4_Naive")
types = list(CD8 = cd8_cells,CD4 = cd4_cells,Treg = "Treg")
for (type_name in  names(types)) {
  source_group = types[[type_name]]
  p = liana_dotplot(liana_mod,
              source_groups = source_group,
                target_groups = target_groups)+ggtitle(type_name)
    print(p)

  pdf(height = 8,width = 15,paste0(params$data_out_dir, 
                                   type_name,"_to_cancer.pdf"))
  print(p)
  dev.off()
  
  write.csv(p$data[,c("source","target","interaction","magnitude","specificity")], file = paste0(params$data_out_dir, type_name,"_to_cancer.csv"), row.names = FALSE)
  

}
```

```{r}
# get luminal - Treg interaction only
liana_mod %>% filter(source == "Treg", target == "Luminal", aggregate_rank <= 0.01) 
```


## all T cells to cancer cells

```{r}
#| fig-height: 8
#| fig-width: 28

p = liana_dotplot(liana_mod,
              source_groups = source_groups,
                target_groups = target_groups)
print(p)
# save_pdf_if_changed(p,target_path = params$data_out_dir %s+% #"all_t_cells_to_cancer.pdf",width = 28,height = 8)
```



##  threshold of 0.01

```{r}
threshold = 0.01
liana_mod <- liana_results %>%
    # Filter to only the cells of interest
    `if`(!is.null(source_groups),
         filter(., source %in% source_groups),
         .) %>%
    `if`(!is.null(target_groups),
         filter(., target %in% target_groups),
         .)

top_interactions = liana_results %>%
  filter(aggregate_rank <= threshold) %>% 
  distinct_at(c("ligand.complex", "receptor.complex"))

liana_mod %<>% inner_join(top_interactions, by=c("ligand.complex", "receptor.complex"))

cd8_cells = c("CD8_CM", "CD8_Naive", "CD8_TEMRA", "CD8_EM")
cd4_cells = c("CD4_EM", "CD4_CM", "CD4_Naive")
types = list(CD8 = cd8_cells,CD4 = cd4_cells,Treg = "Treg")
for (type_name in  names(types)) {
  source_group = types[[type_name]]
  p = liana_dotplot(liana_mod,
              source_groups = source_group,
                target_groups = target_groups)+ggtitle(type_name)
    print(p)

  pdf(height = 8,width = 15,paste0(params$data_out_dir, 
                                   type_name,"_to_cancer_0.01.pdf"))
  print(p)
  dev.off()
  
  write.csv(p$data[,c("source","target","interaction","magnitude","specificity")], file = paste0(params$data_out_dir, type_name,"_to_cancer_0.01.csv"), row.names = FALSE)
  

}
```





# Plot cancer cells to T cells interactions

```{r fig.height=8, fig.width=15}

if (params$debug) {
  print("Running in debug mode, using only 3 cell types and 50 genes for LIANA")
  source_groups = c("Luminal","Myo")
  target_groups = c("CD8_CM")
}else{
  source_groups = c("Luminal","Myo")
  target_groups = c("CD8_CM", 
"gdT", "CD8_Naive", "CD4_EM", 
"CD4_CM", "CD4_Naive", "CD8_TEMRA", "MAIT", "CD8_EM","Treg") 
}
threshold = 0.001
  liana_mod <- liana_results %>%
      # Filter to only the cells of interest
      `if`(!is.null(source_groups),
           filter(., source %in% source_groups),
           .) %>%
      `if`(!is.null(target_groups),
           filter(., target %in% target_groups),
           .)

top_interactions = liana_results %>%
  filter(aggregate_rank <= threshold) %>% 
  distinct_at(c("ligand.complex", "receptor.complex"))

liana_mod %<>% inner_join(top_interactions, by=c("ligand.complex", "receptor.complex"))
cd8_cells = c("CD8_CM", "CD8_Naive", "CD8_TEMRA", "CD8_EM")
cd4_cells = c("CD4_EM", "CD4_CM", "CD4_Naive")
types = list(CD8 = cd8_cells,CD4 = cd4_cells,Treg = "Treg")

for (type_name in  names(types)) {
  target_group = types[[type_name]]
  p = liana_dotplot(liana_mod,
              source_groups = source_groups,
                target_groups = target_group)
  print(p)
  pdf(
    height = 8,
    width = 18,
    paste0(params$data_out_dir, "cancer_to_",type_name,".pdf")
  )
  print(p)
  dev.off()
  
  write.csv(p$data[,c("source","target","interaction","magnitude","specificity")], file = paste0(params$data_out_dir, "cancer_to_",type_name,".csv"), row.names = FALSE)
}
```


## all T cells to cancer cells interactions

```{r}
#| fig-height: 10
#| fig-width: 37
# cancer cells to all T cells interactions

# all T cells to cancer cells
p = liana_dotplot(liana_mod,
              source_groups = source_groups,
                target_groups = target_groups)
print(p)
save_pdf_if_changed(p,target_path = params$data_out_dir %s+% "cancer_to_all_t_cells.pdf",width = 37,height = 10)
```


## switch specificity and magnitude 

```{r}
#| fig-height: 10
#| fig-width: 37
p + aes(x = target, y = interaction, 
        colour = specificity , size = magnitude, group = target)
```


## save for threshold of 0.01

```{r}
# save for threshold of 0.01
threshold = 0.01
  liana_mod <- liana_results %>%
      # Filter to only the cells of interest
      `if`(!is.null(source_groups),
           filter(., source %in% source_groups),
           .) %>%
      `if`(!is.null(target_groups),
           filter(., target %in% target_groups),
           .)

top_interactions = liana_results %>%
  filter(aggregate_rank <= threshold) %>% 
  distinct_at(c("ligand.complex", "receptor.complex"))

liana_mod %<>% inner_join(top_interactions, by=c("ligand.complex", "receptor.complex"))
cd8_cells = c("CD8_CM", "CD8_Naive", "CD8_TEMRA", "CD8_EM")
cd4_cells = c("CD4_EM", "CD4_CM", "CD4_Naive")
types = list(CD8 = cd8_cells,CD4 = cd4_cells,Treg = "Treg")

for (type_name in  names(types)) {
  target_group = types[[type_name]]
  p = liana_dotplot(liana_mod,
              source_groups = source_groups,
                target_groups = target_group)
  print(p)
  pdf(
    height = 8,
    width = 18,
    paste0(params$data_out_dir, "cancer_to_",type_name,"_0.01.pdf")
  )
  print(p)
  dev.off()
  
  write.csv(p$data[,c("source","target","interaction","magnitude","specificity")], file = paste0(params$data_out_dir, "cancer_to_",type_name,"_0.01.csv"), row.names = FALSE)
}
```


#  plot cancer - myeloid immune

```{r fig.height=8, fig.width=15}
#| fig-height: 15
#| fig-width: 15

source_groups = c( "Myeloid Dendritic", "Macrophages", "Basophils", "Neutrophils") 

target_groups = c("Luminal","Myo")

threshold = 0.001
liana_mod <- liana_results %>%
    # Filter to only the cells of interest
    `if`(!is.null(source_groups),
         filter(., source %in% source_groups),
         .) %>%
    `if`(!is.null(target_groups),
         filter(., target %in% target_groups),
         .)

top_interactions = liana_results %>%
  filter(aggregate_rank <= threshold) %>% 
  distinct_at(c("ligand.complex", "receptor.complex"))

liana_mod %<>% inner_join(top_interactions, by=c("ligand.complex", "receptor.complex"))


p = liana_dotplot(liana_mod,
            source_groups = source_groups,
              target_groups = target_groups)
print(p)

pdf(height = 8,width = 15,paste0(params$data_out_dir, 
                                "myeloid_to_cancer.pdf"))
print(p)
dev.off()

write.csv(p$data[,c("source","target","interaction","magnitude","specificity")], file = paste0(params$data_out_dir, "myeloid_to_cancer.csv"), row.names = FALSE)
```