---
title: 'sipsic' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
---
```{r}
library(stringi)
library(Seurat)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(data.table)
library(print.rmd.tabs)
library(grid)
library(ComplexHeatmap)
library(GO.db)
library(GOfuncR)
library(org.Hs.eg.db) 
suppressPackageStartupMessages(library(AnnotationDbi))
suppressPackageStartupMessages(library(SiPSiC))
suppressPackageStartupMessages(library(GSEABase))
```

```{r}
source("./pipe.R")
input = pipeline$sipsic_run$input
output = pipeline$sipsic_run$output
```

```{r}
acc = readRDS(input$acc_cancer_pri)
```

```{r}
canonical_pathways = getGmt(input$canonical_pathways)
```

```{r}
#GO:0002253 activation of immune response
#GO:0002507 tolerance induction
#GO:0002682 regulation of immune system process
#GO:0019882 antigen processing and presentation
#GO:0031294 lymphocyte costimulation
#GO:0045321 leukocyte activation
all_children = get_child_nodes(c('GO:0002253',"GO:0002507","GO:0002682",
                             "GO:0019882","GO:0031294","GO:0045321"))
```


```{r}
all_children = all_children %>% filter(distance<=1)
```


```{r}
# get all genes from all children pathways
results <- AnnotationDbi::select(org.Hs.eg.db, 
                                 keys=c(all_children$child_go_id),
                                 columns = c('SYMBOL'), keytype = 
                                   "GOALL")
#store in a list
go_immune = list()
for (geneset_id in results$GOALL %>% unique()) {
  name = all_children[all_children$child_go_id ==  geneset_id,"child_name"] %>% unique() %>% 
    gsub(pattern = " ", replacement = "_")
  genes = results %>% filter(GOALL == geneset_id) %>% pull(SYMBOL) %>% unique()
  if (any(is.na(genes)) | length(genes) < 5) { #if there are less than 5 genes or some empty, skip
    next
  }
   go_immune[[name]] <- GeneSet(geneIds = genes, setName = name)
}

```



```{r}
#for each pathway, calcualte scores
calculatePathwayScores <- function(pathwayToScore, countsMatrix) {
  pathwayName <- pathwayToScore@setName
  message(pathwayName)
  pathwayGenes <- pathwayToScore@geneIds
  if (!any(pathwayGenes %in% rownames(countsMatrix))) {  # if there are no genes in out data
        return(NA)
  }
  pathwayScoresObject <- getPathwayScores(countsMatrix, pathwayGenes)
  suppressWarnings(
    if (is.null(pathwayScoresObject)) {
      return(NA)
    }
  )
  return(pathwayScoresObject$pathwayScores)
}
```





```{r}
all_pathways_scores = list()
for (patient in unique(acc$patient.ident)) {
  patient_data = subset(acc, subset = patient.ident == patient)
  print(paste0("Calculating scores for patient: ", patient))
  pathwayScoreLists <- lapply(X = go_immune@.Data, calculatePathwayScores, patient_data@assays$RNA@counts)
  names(pathwayScoreLists) = names(go_immune) #set names
  pathwayScoreLists <- pathwayScoreLists[!is.na(pathwayScoreLists)] #remove NA pathways
  pathwayScoresMatrix <- as.data.frame(do.call("rbind", pathwayScoreLists)) # to df
  all_pathways_scores[[patient]] = pathwayScoresMatrix
}
#remove pathways that are not shared between patients
common_pathways = Reduce(intersect, lapply(all_pathways_scores, rownames))
all_pathways_scores = lapply(all_pathways_scores, function(x) x[common_pathways,,drop=F])


#merge all matrix in the list without prefix

pathwayScoresMatrix = do.call("cbind", unname(all_pathways_scores))
```

```{r}
saveRDS(object = pathwayScoresMatrix,file = paste0(params$data_out_dir,basename(output$sipsic_matrix)))
```

```{r}
#TODO: add this path to make pipe
saveRDS(object = go_immune,file = paste0(params$data_out_dir,"immune_genes.rds"))
```

